<script type="text/javascript">
	$(document).ready(function () {
		/*Combo box organigramas*/
		var sourceOrg =
		{
			datatype: "json",
			datafields: [
			{ name: 'id'},
			{ name: 'unidad_administrativa'},
			{ name: 'sigla'},
			],
			url: '/cargos/listorganigrama',
			cache: false,
            async: false
		};
		var dataAdapterOrg = new $.jqx.dataAdapter(sourceOrg);

		$("#organigrama_id").jqxComboBox(
		{
			source: dataAdapterOrg,
			width: 450,
			height: 25,
			promptText: '(Seleccionar)',
			displayMember: 'unidad_administrativa',
			valueMember: 'id'
		}); 

		/*Combo box depende de*/
		var sourceDep =
		{
			datatype: "json",
			datafields: [
			{ name: 'organigrama'},
			{ name: 'id'},
			{ name: 'codigo'},
			{ name: 'cargo'},
			],
			url: '/cargos/listdepende',
			cache: false,
			async: false
		};
		var dataAdapterDep = new $.jqx.dataAdapter(sourceDep);

		$("#depende_id").jqxComboBox(
		{
			//source: dataAdapterDep,
			width: 450,
			height: 25,
			disabled: false ,
			promptText: '(Seleccionar)',
			displayMember: 'cargo',
			valueMember: 'id',
			autoDropDownHeight: true
		}); 

		/*Filtro segun organigrama a cargos*/
		
		$("#organigrama_id").bind('select', function(event)
		{
			if (event.args)
			{
				$("#depende_id").jqxComboBox({ disabled: false, selectedIndex: -1});		
				var value = event.args.item.value;
				sourceDep.data = {organigrama_id: value};
				dataAdapterDep = new $.jqx.dataAdapter(sourceDep);
				$("#depende_id").jqxComboBox({source: dataAdapterDep});
			}
		}); 




		/*Combo box nivel salarial*/
		var source =
		{
			datatype: "json",
			datafields: [
			{ name: 'id'},
			{ name: 'denominacion'},
			{ name: 'sueldo'},
			],
			url: '/cargos/listnivelsalarial',
			async: false
		};
		var dataAdapter = new $.jqx.dataAdapter(source);

		$("#nivelsalarial_id").jqxComboBox(
		{
			source: dataAdapter,
			width: 450,
			height: 25,
			promptText: '(Seleccionar)',
			displayMember: 'denominacion',
			valueMember: 'id'
			
		});       		

		$('#nivelsalarial_id').bind('select', function (event) { 
			var v=$.ajax({
				url:'/cargos/getSueldo/',
				type:'POST',
				datatype: 'json',
				data:{id:$('#nivelsalarial_id').jqxComboBox('val')},
				success: function(data) { $("#sueldotxt").text(data);
												}, //mostramos el error
												error: function() { alert('Se ha producido un error Inesperado'); }
											});
		});
		
		
		cargar();	

		function cargar(){
			var source =
			{
				datatype: "json",
				datafields: [
				{ name: 'nro',type: 'number'},
				{ name: 'id',type: 'number'},
				{ name: 'unidad_administrativa',type: 'string'},
				{ name: 'organigrama_id',type: 'string'},
				{ name: 'depende_id',type: 'number'},
				{ name: 'nivelsalarial_id',type: 'string'},
				{ name: 'denominacion',type: 'string'},
				{ name: 'codigo',type: 'string'},
				{ name: 'cargo',type: 'string'},
				{ name: 'sueldo'},
				{ name: 'fin_partida_id'},
				{ name: 'estado', type: 'string'},
				{ name: 'cargo_estado_id'},
				{ name: 'condicion', type: 'string'}
				],
				url: '/cargos/list',
				cache: false
			};

			var dataAdapter = new $.jqx.dataAdapter(source);
			$("#jqxgrid").jqxGrid({
				width: '100%',
				source: dataAdapter,
				sortable: true,
				altRows: true,
				pageable: true,
				pagerMode: 'advanced',
				showfilterrow: true,
				filterable: true,
				autorowheight: true,
                autoheight: true,
				columns: [
				{ text: 'Nro', datafield: 'nro',filtertype: 'number', width: '3%'},
				{ text: 'Organigrama', datafield: 'unidad_administrativa', filtertype: 'input',width: '20%' },
				{ text: 'Denominacion', datafield: 'denominacion', filtertype: 'input',width: '15%' },
				{ text: 'Item', datafield: 'codigo', filtertype: 'input',width: '5%' },
				{ text: 'Cargo', datafield: 'cargo', filtertype: 'input',width: '30%' },
				{ text: 'Salario Mensual', datafield: 'sueldo', filtertype: 'number',width: '5%' },
				{ text: 'Estado', datafield: 'estado', filtertype: 'checkedlist',width: '7%' },
				{ text: 'Tipo Cargo', datafield: 'condicion', filtertype: 'checkedlist',width: '5%' },
				{ text: 'Editar', datafield: 'Editar', width: '5%',sortable:false, columntype: 'button',filterable:false, cellsrenderer: function () {
					return "Editar";
				}, buttonclick: function (row) {
                     // open the popup window when the user clicks a button.
                     editrow = row;
                     var offset = $("#jqxgrid").offset();
                     $("#popupWindow").jqxWindow({ position: { x: parseInt(offset.left) + 60, y: parseInt(offset.top) + 60 } });

                     // get the clicked row's data and initialize the input fields.
                     var dataRecord = $("#jqxgrid").jqxGrid('getrowdata', editrow);
                     $("#titulo").text("Editar");
                     $("#id").val(dataRecord.id);
                     $("#organigrama_id").val(dataRecord.organigrama_id);
                     $("#depende_id").val(dataRecord.depende_id);
                     $("#nivelsalarial_id").val(dataRecord.nivelsalarial_id);
                     $("#codigo").val(dataRecord.codigo);
                     $("#cargo").val(dataRecord.cargo);
                     //$("#nivelsalarial_id").val(dataRecord.nivelsalarial_id);
                     //$("#cargo_estado_id").val(dataRecord.cargo_estado_id);
                     $("#sueldotxt").text(dataRecord.sueldo);
                     //$("[type=radio][name=cargo_estado_id][value=" + dataRecord.cargo_estado_id + "]").attr("checked", "checked");
                     $('input[name=cargo_estado_id][value="' + dataRecord.cargo_estado_id + '"]').prop('checked', true);
                     //$("#fin_partida_id").val(dataRecord.fin_partida_id);
                     //$("#fin_partida_id").attr('disabled', 'disabled');

                     // show the popup window.
                     $("#popupWindow").jqxWindow('open');
                 }
             },
             { text: 'Eliminar', datafield: 'Eliminar',width:'5%', sortable:false, columntype: 'button',filterable:false, cellsrenderer: function () {
             	return "Eliminar";
             }, buttonclick: function (row) {
             	editrow = row;
             	var offset = $("#jqxgrid").offset();
             	$("#popupWindow_delete").jqxWindow({ position: { x: parseInt(offset.left) + 60, y: parseInt(offset.top) + 60 } });

             	var dataRecord = $("#jqxgrid").jqxGrid('getrowdata', editrow);
             	$("#id").val(dataRecord.id);
             	$("#popupWindow_delete").jqxWindow('open');
             }
         	}
         ]
     });

}
$("#jqxgrid").bind('rowselect', function (event) {
					var dataRecord = $("#jqxgrid").jqxGrid('getrowdata', event.args.rowindex);
					//alert(dataRecord.estado);
					$("#cargo_id_pac").val(dataRecord.id);
					$("#estado_cargo").val(dataRecord.estado);
					$("#organigrama_pac").text(dataRecord.unidad_administrativa);
					$("#item_pac").text(dataRecord.codigo);
					$("#cargo_pac").text(dataRecord.cargo);
					$("#sueldo_pac").text(dataRecord.sueldo);
				});

/*segundo grid*/

cargar2();	
function cargar2(){
	var source =
	{
		datatype: "json",
		datafields: [
		{ name: 'nro',type: 'number'},
		{ name: 'id',type: 'number'},
		{ name: 'unidad_administrativa',type: 'string'},
		{ name: 'cargo',type: 'string'},
		{ name: 'estado',type: 'string'},
		{ name: 'gestion',type: 'string'},
		{ name: 'fecha_ini',type:'date'},
		{ name: 'fecha_fin',type:'date'}
		],
		url: '/cargos/listpac',
		cache: false
	};

	var dataAdapter = new $.jqx.dataAdapter(source);
	$("#jqxgrid2").jqxGrid({
		width: '100%',
		source: dataAdapter,
		sortable: true,
		altRows: true,
		pageable: true,
		pagerMode: 'advanced',
		showfilterrow: true,
		filterable: true,
		columns: [
		{ text: 'Nro', datafield: 'nro',filtertype: 'number', width: '3%'},
		{ text: 'Organigrama', datafield: 'unidad_administrativa', filtertype: 'input',width: '30%' },
		{ text: 'Cargo', datafield: 'cargo', filtertype: 'input',width: '30%' },
		{ text: 'Gestion', datafield: 'gestion', filtertype: 'number',width: '5%' },
		{ text: 'Fecha Inicio', datafield: 'fecha_ini', filtertype: 'range', width: '10%', cellsalign: 'center', cellsformat: 'dd-MM-yyyy', align:'center'},
		{ text: 'Fecha Finalización', datafield: 'fecha_fin', filtertype: 'range', width: '10%', cellsalign: 'center', cellsformat: 'dd-MM-yyyy', align:'center'},
		{ text: 'Estado', datafield: 'estado', filtertype: 'input',width: '5%' },
		{ text: '', datafield: 'Eliminar',width:'5%', sortable:false, columntype: 'button',filterable:false, cellsrenderer: function () {
             	return "Eliminar";
             }, buttonclick: function (row) {
             	editrow = row;
             	var offset = $("#jqxgrid2").offset();
             	$("#popupWindow_delete_pac").jqxWindow({ position: { x: parseInt(offset.left) + 60, y: parseInt(offset.top) + 60 } });

             	var dataRecord = $("#jqxgrid2").jqxGrid('getrowdata', editrow);
             	$("#id").val(dataRecord.id);
             	//alert(dataRecord.estado);
             	if (dataRecord.estado!=null) {
             		alert("MENSAJE: El cargo esta en proceso de contratacion.!!!");
             	}else{
             		$("#popupWindow_delete_pac").jqxWindow('open');
             	}
             	
             }
        }
		]
	});

}

/*******end segungo grid*********/
		// initialize the popup window and buttons.
		$("#popupWindow").jqxWindow({
			width: 850,height:500, resizable: false,  isModal: true, autoOpen: false, cancelButton: $("#Cancel"), modalOpacity: 0.01           
		});
		$("#popupWindow_delete").jqxWindow({
			width: 850, resizable: false,  isModal: true, autoOpen: false, cancelButton: $("#Cancel"), modalOpacity: 0.01           
		});
		$("#popupWindow_delete_pac").jqxWindow({
			width: 850, resizable: false,  isModal: true, autoOpen: false, cancelButton: $("#Cancel"), modalOpacity: 0.01           
		});

		$("#popupWindow_pac").jqxWindow({
			width: 850, height:500,resizable: false,  isModal: true, autoOpen: false, cancelButton: $("#Cancel"), modalOpacity: 0.01           
		});
            // update the edited row when the user clicks the 'Save' button.
            $("#add").click(function(){
            	$("#titulo").text("Adicionar");
            	$("#id").val("");
            	$("[type=radio][name=cargo_estado_id]:checked").removeAttr("checked");
            	$("#codigo").val("");
            	$("#organigrama_id").val("");
            	$("#nivelsalarial_id").val("");
            	$("#cargo").val("");
            	$("#sueldotxt").text("");
            	$('input[name=cargo_estado_id][value="1"]').prop('checked', true);
            	$("#popupWindow").jqxWindow('open');
            });

            $("#add_pac").click(function(){
            	if($("#cargo_id_pac").val()!=""){
            		if ($("#estado_cargo").val()=='ADJUDICADO') {
            			alert("MENSAJE: El cargo ya esta ADJUDICADO.");	
            		}else{
            			//alert($("#cargo_id_pac").val());
            			var v=$.ajax({
            				url:'/cargos/getEstadoSeguimiento/',
            				type:'POST',
            				datatype: 'json',
            				data:{cargo_id:$("#cargo_id_pac").val()},
            				success: function(data) { 
            					//alert(data);
            					if(data==1 && data=="null"){
            						alert("MENSAJE: El cargo ya esta en proceso o esta en el PAC.");	
            					}else{
            						$("#popupWindow_pac").jqxWindow('open');					
            					}

												}, //mostramos el error
												error: function() { alert('Se ha producido un error Inesperado'); }
											});

            			
            		}
            	}else{
            		alert("MENSAJE: Seleccione un registro ...");
            	}
            	
            });

            $("#Save").click(function () {
            	if ($('#testForm').jqxValidator('validate')){
            	var cargo_estado_id = $('input[name="cargo_estado_id"]:checked').val();        
  				//alert(cargo_estado_id); 
  				var v=$.ajax({
  					url:'/cargos/save/',
  					type:'POST',
  					datatype: 'json',
  					data:{id:$("#id").val(),organigrama_id:$('#organigrama_id').jqxComboBox('val'),depende_id:$('#depende_id').jqxComboBox('val'),cargo:$("#cargo").val(),nivelsalarial_id:$("#nivelsalarial_id").jqxComboBox('val'),cargo_estado_id:cargo_estado_id,codigo:$('#codigo').val()},
						success: function(data) { cargar(); //alert(data.msm); 
												}, //mostramos el error
												error: function() { alert('Se ha producido un error Inesperado'); }
											});
  				$("#popupWindow").jqxWindow('hide');
                }
           });

            $("#guardar_pac").click(function () {
            	if ($('#testForm_pac').jqxValidator('validate')){
            	var fecha_ini = $('#fecha_ini_pac').jqxDateTimeInput('getDate');
            	var fecha_fin = $('#fecha_fin_pac').jqxDateTimeInput('getDate');
            	var v=$.ajax({
  					url:'/cargos/save_pac/',
  					type:'POST',
  					datatype: 'json',
  					data:{cargo_id_pac:$("#cargo_id_pac").val(),gestion:$('#gestion_pac').val(),fecha_ini:fecha_ini,fecha_fin:fecha_fin},
						success: function(data) { cargar2(); //alert(data); 
												}, //mostramos el error
												error: function() { alert('Se ha producido un error Inesperado'); }
											});
  				$("#popupWindow_pac").jqxWindow('hide');
                }
           });

            $("#Eliminar").click(function () {
            	if (editrow >= 0) {
            		var v=$.ajax({
            			url:'/cargos/delete/',
            			type:'POST',
            			datatype: 'json',
            			data:{id:$("#id").val()},
						success: function(data) { cargar(); //alert('Guardado Correctamente'); 
												}, //mostramos el error
												error: function() { alert('Se ha producido un error Inesperado'); }
											});
					//$('#jqxgrid').jqxGrid();
					$("#popupWindow_delete").jqxWindow('hide');
				}
			});

			$("#Eliminar_pac").click(function () {
            	if (editrow >= 0) {
            		var v=$.ajax({
            			url:'/cargos/delete_pac/',
            			type:'POST',
            			datatype: 'json',
            			data:{id:$("#id").val()},
						success: function(data) { cargar2(); //alert('Guardado Correctamente'); 
												}, //mostramos el error
												error: function() { alert('Se ha producido un error Inesperado'); }
											});
					//$('#jqxgrid').jqxGrid();
					$("#popupWindow_delete_pac").jqxWindow('hide');
				}
			});

            $("#nivelsalarial_id").change(function(){
            	var element = $(this).find('option:selected'); 
            	var myTag = element.attr("sueldo"); 
            	$('#sueldotxt').text(myTag);
            });

            $("#fecha_ini_pac").jqxDateTimeInput({width: '250px', height: '25px',formatString:'dd-MM-yyyy'});
            $("#fecha_fin_pac").jqxDateTimeInput({width: '250px', height: '25px',formatString:'dd-MM-yyyy'});
            
            $('#testForm').jqxValidator({
                rules: [
                       	{ input: "#organigrama_id input", message: "Campo requerido!", action: 'blur', rule: function (input, commit) {
    						var index = $("#organigrama_id").jqxComboBox('getSelectedIndex');
    						return index != -1;
							}
						},
						
                       { input: "#nivelsalarial_id input", message: "Campo requerido!", action: 'blur', rule: function (input, commit) {
    						var index = $("#nivelsalarial_id").jqxComboBox('getSelectedIndex');
    						return index != -1;
							}
						},
                       { input: '#codigo', message: 'Campo requerido!', action: 'keyup, blur', rule: 'required' },
                       /*{ input: "#codigo", message: "Item ", action: 'blur', rule: function () {
                       		if ($("#codigo").val()=='') {
                       			return false;
                       		}else{
                       			return true;
                       			}
                       		
                       		var v=$.ajax({
			            			url:'/cargos/itemDuplicado/',
			            			type:'POST',
			            			datatype: 'json',
			            			data:{id:$("#codigo").val()},
									success: function(data) { ; //alert('Guardado Correctamente'); 
															}, //mostramos el error
															error: function() { alert('Se ha producido un error Inesperado'); }
									});
                       		}
						},*/
                       { input: '#cargo', message: 'Campo requerido!', action: 'keyup, blur', rule: 'required' }
                       
                       ]
            });

			$('#testForm_pac').jqxValidator({
                rules: [
                       { input: '#gestion_pac', message: 'Campo requerido!', action: 'keyup, blur', rule: 'required' }
                       ]
            });

        });
</script>

<div class="row">
	<div class="col-lg-12">
		<h3>Cargos</h3>		
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			
			<?php //echo $this->flashSession->output() ?>
			<div style="margin-left: 5px;float:left">
				<div>
					<input id="add" type="button" value=" (+) Adicionar" />&nbsp;&nbsp;&nbsp;
				</div>
			</div> 
			<div style="margin-left: 5px; ">
				<div>
					<input id="add_pac" type="button" value=" Asignar PAC" />
				</div>
			</div>
			<br>
			<div class="table-responsive">
				<div id="jqxgrid"></div>
			</div>
			<div style="margin-top: 30px;">
				<div id="cellbegineditevent"></div>
				<div style="margin-top: 10px;" id="cellendeditevent"></div>
			</div>
			<div id="popupWindow">
				<div id="titulo">Editar</div>
				<div style="overflow: hidden;">
					<form id="testForm">
					<table>
						<tr>
							<td align="right">id:</td>
							<td align="left"><input id="id" name="id" type="hidden" /></td>
						</tr>
						<tr>
							<td align="right">Organigrama:</td>
							<td align="left" ><?php // echo $organigrama ?>
								<div name="list" id="organigrama_id" ></div>
							</td>
						</tr>
						<tr>
							<td align="right">Depende de:</td>
							<td align="left" >
								<div name="list_depende_id" id="depende_id" ></div>
							</td>
						</tr>
						<tr>
							<td align="right">Nivel Salarial:</td>
							<td align="left">
								<div name="list2" id="nivelsalarial_id" ></div>
							</td>
						</tr>
						<tr>
							<td align="right">Salario Mensual:</td>
							<td align="left" class="form-control"><span id="sueldotxt"></span> Bs.</td>
						</tr>
						<tr>
							<td align="right">Item:</td>
							<td align="left"><input id="codigo" name="codigo" type="text" class="form-control"/></td>
						</tr>
						<tr>
							<td align="right">Cargo:</td>
							<td align="left"><input id="cargo" name="cargo" type="text" class="form-control"/></td>
						</tr>
						<tr>
							<td align="right">Tipo Cargo:</td>
							<td align="left">
								<!-- <div data-toggle="buttons">-->
								<div class="form-control">
									<?php foreach ($cargoestado as $v) { ?>
									<!-- <label class="btn btn-primary btn-xs"> -->

									<input type="radio" name="cargo_estado_id" value="<?php echo $v->id ?>"/> <?php echo $v->estado; ?>


									<?php } ?>

								</div>
							</td>
						</tr>
						<tr>
							<td align="right"></td>
							<td style="padding-top: 10px;" align="right">
								<input style="margin-right: 5px;" type="button" id="Save" value="Guardar" />
								<input id="Cancel" type="button" value="Cancelar" />
							</td>
						</tr>
					</table>
					</form>
				</div>
			</div>

			<div id="popupWindow_delete">
				<div>Eliminar</div>
				<div style="overflow: hidden;">
					<table>
						<tr>
							<td align="left">Esta seguro de Eliminar el registro</td>
						</tr>
						<tr>
							<td align="right"></td>
							<td style="padding-top: 10px;" align="right">
								<input style="margin-right: 5px;" type="button" id="Eliminar" value="Eliminar" />
								<input id="Cancel" type="button" value="Cancelar" />
							</td>
						</tr>
					</table>
				</div>
			</div>

			<div id="popupWindow_delete_pac">
				<div>Eliminar</div>
				<div style="overflow: hidden;">
					<table>
						<tr>
							<td align="left">Esta seguro de Eliminar el registro</td>
						</tr>
						<tr>
							<td align="right"></td>
							<td style="padding-top: 10px;" align="right">
								<input style="margin-right: 5px;" type="button" id="Eliminar_pac" value="Eliminar" />
								<input id="Cancel" type="button" value="Cancelar" />
							</td>
						</tr>
					</table>
				</div>
			</div>

			<div id="popupWindow_pac">
				<div>REGISTRAR EN EL PLAN ANUAL DE CONTRATACIONES</div>
				<div style="overflow: hidden;">
				<form id="testForm_pac">
					<input id="cargo_id_pac" name="cargo_id_pac" type="hidden" />
					<input id="estado_cargo" name="estado_cargo" type="hidden" />
					<table>
						<tr>
							<td align="right">Organigrama:</td>
							<td align="left" ><div id="organigrama_pac"></div></td>
						</tr>
						<tr>
							<td align="right">Item:</td>
							<td align="left"><div id="item_pac"></div></td>
						</tr>
						<tr>
							<td align="right">Cargo:</td>
							<td align="left"><div id="cargo_pac"></div></td>
						</tr>
						<tr>
							<td align="right">Salario Mensual:</td>
							<td align="left"><div id="sueldo_pac"></div></td>
						</tr>
						<tr>
							<td align="right">Gestión:</td>
							<td align="left"><input id="gestion_pac" name="gestion_pac" type="text" value="<?php echo date("Y"); ?>" /></td>
						</tr>
						<tr>
							<td align="right">Fecha Inicio:</td>
							<td align="left"><div id="fecha_ini_pac"></div></td>
						</tr>
						<tr>
							<td align="right">Fecha Finalización:</td>
							<td align="left"><div id="fecha_fin_pac"></div></td>
						</tr>
						<tr>
							<td align="right"></td>
							<td style="padding-top: 10px;" align="right">
								<input style="margin-right: 5px;" type="button" id="guardar_pac" value="Guardar" />
								<input id="Cancel" type="button" value="Cancel" />
							</td>
						</tr>
					</table>
				</form>
				</div>
			</div>


		</div>
	</div>

	
</div>

<div class="row">
	<div class="col-lg-12">
		<h3>Plan Anual de Contrataciones</h3>	
	</div>

	<div class="col-lg-12">
		<div class="panel panel-default">
			
			<div class="table-responsive">
				<div id="jqxgrid2"></div>
			</div>
			
		</div>
	</div>

</div>

