<script type="text/javascript">
$(document).ready(function () {
/*Combo box organigramas*/
var source =
		{
			datatype: "json",
			datafields: [
			{ name: 'id'},
			{ name: 'unidad_administrativa'},
			{ name: 'sigla'},
			],
			url: '/cargos/listorganigrama',
			async: false
		};
		var dataAdapter = new $.jqx.dataAdapter(source);
			
		$("#organigrama_id").jqxComboBox(
		{
			source: dataAdapter,
			width: 450,
			height: 25,
			promptText: '(Seleccionar)',
			displayMember: 'unidad_administrativa',
			valueMember: 'id'
		}); 

/*Combo box nivle salarial*/
var source =
		{
			datatype: "json",
			datafields: [
			{ name: 'id'},
			{ name: 'denominacion'},
			{ name: 'sueldo'},
			],
			url: '/cargos/listnivelsalarial',
			async: false
		};
		var dataAdapter = new $.jqx.dataAdapter(source);
			
		$("#nivelsalarial_id").jqxComboBox(
		{
			source: dataAdapter,
			width: 450,
			height: 25,
			promptText: '(Seleccionar)',
			displayMember: 'denominacion',
			valueMember: 'id'
			
		});       		

$('#nivelsalarial_id').bind('select', function (event) { 
	/*var args = event.args;
    var item = $('#nivelsalarial_id').jqxComboBox('getItem', args.index);
    alert($('#nivelsalarial_id').jqxComboBox('val'))
    */
    //alert(dataAdapter.sueldo);
    var v=$.ajax({
                    	url:'../../cargos/getSueldo/',
                    	type:'POST',
                    	datatype: 'json',
						data:{id:$('#nivelsalarial_id').jqxComboBox('val')},
						success: function(data) { $("#sueldotxt").text(data);
												}, //mostramos el error
						error: function() { alert('Se ha producido un error Inesperado'); }
					});
});

/**Ponemos un valor por defaul**/
/*var item = $("#organigrama_id").jqxComboBox("getItemByValue", 7);
$("#organigrama_id").jqxComboBox("selectItem", item);
*/

		
		
		var source =
		{
			datatype: "json",
			datafields: [
				{ name: 'id',type: 'number'},
				{ name: 'unidad_administrativa',type: 'string'},
				{ name: 'organigrama_id',type: 'string'},
				{ name: 'nivelsalarial_id',type: 'string'},
				{ name: 'denominacion',type: 'string'},
				{ name: 'codigo',type: 'string'},
				{ name: 'cargo',type: 'string'},
				{ name: 'sueldo'},
				{ name: 'fin_partida_id'},
				{ name: 'estado', type: 'string'},
				{ name: 'cargo_estado_id'},
				{ name: 'condicion', type: 'string'}
			],
			url: '/cargos/list',
			cache: false
		};

		var dataAdapter = new $.jqx.dataAdapter(source);
		cargar();	
		function cargar(){
			$("#jqxgrid").jqxGrid(
		{
		width: '100%',
		source: dataAdapter,
		sortable: true,
		altRows: true,
		pageable: true,
		pagerMode: 'advanced',
		showfilterrow: true,
		filterable: true,
		columns: [
			{ text: 'Nro', datafield: 'id',filtertype: 'number', width: '3%'},
			{ text: 'Organigrama', datafield: 'unidad_administrativa', filtertype: 'input',width: '20%' },
			//{ text: 'Unidad Ejecutora', datafield: 'unidad_ejecutora', filtertype: 'input',width: '20%' },
			{ text: 'Denominacion', datafield: 'denominacion', filtertype: 'input',width: '15%' },
			{ text: 'Codigo', datafield: 'codigo', filtertype: 'input',width: '5%' },
			{ text: 'Cargo', datafield: 'cargo', filtertype: 'input',width: '30%' },
			{ text: 'Salario Mensual', datafield: 'sueldo', filtertype: 'number',width: '5%' },
			{ text: 'Estado', datafield: 'estado', filtertype: 'checkedlist',width: '7%' },
			{ text: 'Tipo Cargo', datafield: 'condicion', filtertype: 'checkedlist',width: '5%' },
			{ text: 'Editar', datafield: 'Editar', width: '5%',sortable:false, columntype: 'button',filterable:false, cellsrenderer: function () {
                     return "Editar";
                  }, buttonclick: function (row) {
                     // open the popup window when the user clicks a button.
                     editrow = row;
                     var offset = $("#jqxgrid").offset();
                     $("#popupWindow").jqxWindow({ position: { x: parseInt(offset.left) + 60, y: parseInt(offset.top) + 60 } });

                     // get the clicked row's data and initialize the input fields.
                     var dataRecord = $("#jqxgrid").jqxGrid('getrowdata', editrow);
                     $("#titulo").text("Editar");
                     $("#id").val(dataRecord.id);
                     $("#organigrama_id").val(dataRecord.organigrama_id);
                     $("#nivelsalarial_id").val(dataRecord.nivelsalarial_id);
                     $("#codigo").val(dataRecord.codigo);
                     $("#cargo").val(dataRecord.cargo);
                     //$("#nivelsalarial_id").val(dataRecord.nivelsalarial_id);
                     //$("#cargo_estado_id").val(dataRecord.cargo_estado_id);
                     $("#sueldotxt").text(dataRecord.sueldo);
                     //$("[type=radio][name=cargo_estado_id][value=" + dataRecord.cargo_estado_id + "]").attr("checked", "checked");
                     $('input[name=cargo_estado_id][value="' + dataRecord.cargo_estado_id + '"]').prop('checked', true);
                     //$("#fin_partida_id").val(dataRecord.fin_partida_id);
                     //$("#fin_partida_id").attr('disabled', 'disabled');

                     // show the popup window.
                     $("#popupWindow").jqxWindow('open');
                 }
            },
            { text: 'Eliminar', datafield: 'Eliminar',width:'5%', sortable:false, columntype: 'button',filterable:false, cellsrenderer: function () {
                     return "Eliminar";
                  }, buttonclick: function (row) {
                     editrow = row;
                     var offset = $("#jqxgrid").offset();
                     $("#popupWindow_delete").jqxWindow({ position: { x: parseInt(offset.left) + 60, y: parseInt(offset.top) + 60 } });

                     var dataRecord = $("#jqxgrid").jqxGrid('getrowdata', editrow);
                     $("#id").val(dataRecord.id);
                     $("#popupWindow_delete").jqxWindow('open');
                 }
            }
		]
		});

		}



/*segundo grid*/
/*var source =
		{
			datatype: "json",
			datafields: [
				{ name: 'id2',type: 'number'},
				{ name: 'unidad_administrativa2',type: 'string'},
				{ name: 'cargo2',type: 'string'},
				{ name: 'gestion2',type: 'string'},
				{ name: 'fecha_ini2',type: 'string'},
				{ name: 'fecha_fin2',type: 'string'},
			],
			url: '/cargos/listpac',
			cache: false
		};

		var dataAdapter = new $.jqx.dataAdapter(source);
		cargar2();	
		function cargar2(){
			$("#jqxgrid2").jqxGrid(
		{
		width: '100%',
		source: dataAdapter,
		sortable: true,
		altRows: true,
		pageable: true,
		pagerMode: 'advanced',
		showfilterrow: true,
		filterable: true,
		columns: [
			{ text: 'Nro', datafield: 'id2',filtertype: 'number', width: '3%'},
			{ text: 'Organigrama', datafield: 'unidad_administrativa2', filtertype: 'input',width: '30%' },
			{ text: 'Cargo', datafield: 'cargo2', filtertype: 'input',width: '30%' },
			{ text: 'Gestion', datafield: 'gestion2', filtertype: 'number',width: '5%' },
			{ text: 'Fecha Inicio', datafield: 'fecha_ini2', filtertype: 'input',width: '10%' },
			{ text: 'Fecha Finalizacion', datafield: 'fecha_fin2', filtertype: 'input',width: '10%' },
		]
		});

		}
		*/
/*******end segungo grid*********/




		// initialize the popup window and buttons.
            $("#popupWindow").jqxWindow({
                width: 850,height:500, resizable: false,  isModal: true, autoOpen: false, cancelButton: $("#Cancel"), modalOpacity: 0.01           
            });
            $("#popupWindow_delete").jqxWindow({
                width: 850, resizable: false,  isModal: true, autoOpen: false, cancelButton: $("#Cancel"), modalOpacity: 0.01           
            });
            // update the edited row when the user clicks the 'Save' button.
            $("#add").click(function(){
            	$("#titulo").text("Adicionar");
            	$("#id").val("");
            	$("[type=radio][name=cargo_estado_id]:checked").removeAttr("checked");
            	$("#codigo").val("");
            	$("#organigrama_id").val("");
            	$("#nivelsalarial_id").val("");
            	$("#cargo").val("");
            	$("#sueldotxt").text("");
            	//$('#fin_partida_id').val(0);
            	//$('#fin_partida_id').removeAttr('disabled');
            	$("#cargo_estado_id").val("");
            	$("#popupWindow").jqxWindow('open');
            });

            $("#Save").click(function () {
            	var cargo_estado_id = $('input[name="cargo_estado_id"]:checked').val();        
  				//alert(cargo_estado_id); 
            	var v=$.ajax({
                    	url:'../../cargos/save/',
                    	type:'POST',
                    	datatype: 'json',
						data:{id:$("#id").val(),organigrama_id:$('#organigrama_id').jqxComboBox('val'),cargo:$("#cargo").val(),nivelsalarial_id:$("#nivelsalarial_id").jqxComboBox('val'),cargo_estado_id:cargo_estado_id,codigo:$('#codigo').val()},
						success: function(data) { cargar(); //alert(data.msm); 
												}, //mostramos el error
						error: function() { alert('Se ha producido un error Inesperado'); }
					});
                    $("#popupWindow").jqxWindow('hide');
               // }
            });

            $("#Eliminar").click(function () {
            	if (editrow >= 0) {
                    var v=$.ajax({
                    	url:'../../cargos/delete/',
                    	type:'POST',
                    	datatype: 'json',
						data:{id:$("#id").val()},
						success: function(data) { cargar(); //alert('Guardado Correctamente'); 
												}, //mostramos el error
						error: function() { alert('Se ha producido un error Inesperado'); }
					});
					//$('#jqxgrid').jqxGrid();
                    $("#popupWindow_delete").jqxWindow('hide');
                }
            });

            $("#nivelsalarial_id").change(function(){
           	var element = $(this).find('option:selected'); 
        	var myTag = element.attr("sueldo"); 
            $('#sueldotxt').text(myTag);
        });

	});
</script>

<div class="row">
	<div class="col-lg-12">
		<h3>Cargos</h3>		
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-body">
				<?php //echo $this->flashSession->output() ?>
				<div style="margin-left: 5px;">
					<div>
						<input id="add" type="button" value=" (+) Adicionar" />
					</div>
				</div>
				<br>
				<div class="table-responsive">
					<div id="jqxgrid"></div>
				</div>
				<div style="margin-top: 30px;">
            		<div id="cellbegineditevent"></div>
            		<div style="margin-top: 10px;" id="cellendeditevent"></div>
       			</div>
				<div id="popupWindow">
					<div id="titulo">Editar</div>
					<div style="overflow: hidden;">
						<table>
							<tr>
								<td align="right">id:</td>
								<td align="left"><input id="id" name="id" type="hidden" /></td>
							</tr>
							<tr>
								<td align="right">Organigrama:</td>
								<td align="left" ><?php // echo $organigrama ?>
									<div name="list" id="organigrama_id" ></div>
								</td>
							</tr>
							<tr>
								<td align="right">Nivel Salarial:</td>
								<td align="left">
									<div name="list2" id="nivelsalarial_id" ></div>
									
								</td>
							</tr>
							<tr>
								<td align="right">Salario Mensual:</td>
								<td align="left" class="form-control"><span id="sueldotxt"></span> Bs.</td>
							</tr>
							<tr>
								<td align="right">Codigo:</td>
								<td align="left"><input id="codigo" name="codigo" type="text" class="form-control"/></td>
							</tr>
							<tr>
								<td align="right">Cargo:</td>
								<td align="left"><input id="cargo" name="cargo" type="text" class="form-control"/></td>
							</tr>
							<tr>
								<td align="right">Tipo Cargo:</td>
								<td align="left">
									<!-- <div data-toggle="buttons">-->
									<div class="form-control">
									<?php foreach ($cargoestado as $v) { ?>
										<!-- <label class="btn btn-primary btn-xs"> -->
										
                    						<input type="radio" name="cargo_estado_id" value="<?php echo $v->id ?>"/> <?php echo $v->estado; ?>
                						
										
									<?php } ?>
                
            						</div>
            					</td>
							</tr>
							<tr>
								<td align="right"></td>
								<td style="padding-top: 10px;" align="right">
								<input style="margin-right: 5px;" type="button" id="Save" value="Save" />
								<input id="Cancel" type="button" value="Cancel" />
								</td>
							</tr>
						</table>
					</div>
				</div>

				<div id="popupWindow_delete">
					<div>Eliminar</div>
					<div style="overflow: hidden;">
						<table>
							<tr>
								<td align="left">Esta seguro de Eliminar el registro</td>
							</tr>
							<tr>
								<td align="right"></td>
								<td style="padding-top: 10px;" align="right">
								<input style="margin-right: 5px;" type="button" id="Eliminar" value="Eliminar" />
								<input id="Cancel" type="button" value="Cancel" />
								</td>
							</tr>
						</table>
					</div>
				</div>

			</div>
		</div>
		
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<h3>Plan Anual de Contrataciones</h3>	
	</div>

	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="table-responsive">
					<div id="jqxgrid2"></div>
				</div>
			</div>
		</div>
	</div>

</div>

