<div class="row">
	<div class="col-lg-12">
		<h1>Editar Unidad Administrativa</h1>		
	</div>
</div>
<div class="row">
	<div class="col-lg-6">
		<form method="post" action="" class="form-horizontal">
		<input type="hidden" name="id" value="<?php echo $organigrama->id ?>">
			<div class="form-group">
				<label class="col-lg-2 control-label">Depende de</label>
				<div class="col-lg-10">
					<?php echo $padre; ?>
				</div>
			</div>
			<div class="form-group">
				<label class="col-lg-2 control-label">Nivel Estructural</label>
				<div class="col-lg-10">
					<?php echo $nivelestructural; ?>
				</div>
			</div>
			<div class="form-group">
				<label class="col-lg-2 control-label">Nivel Estructural</label>
				<div class="col-lg-10">
					<input type="text" name="unidad_administrativa" value="<?php echo $organigrama->unidad_administrativa ?>" class="form-control" placeholder="ingrese unidad administrativa" required>
				</div>
			</div>
			<div class="form-group">
				<label class="col-lg-2 control-label">Sigla</label>
				<div class="col-lg-10">
					<input type="text" name="sigla" id="sigla" class="form-control" placeholder="ingrese sigla" value="<?php echo $organigrama->sigla ?>" required>
				</div>
			</div>
			<div class="form-group">
				<label class="col-lg-2 control-label">Area</label>
				<div class="col-lg-10">
					<input type="radio" name="area_sustantiva" value="1" <?php if ($organigrama->area_sustantiva==1) {	echo "checked"; } ?>  /> Sustantiva o Misional
					<input type="radio" name="area_sustantiva" value="0" <?php if ($organigrama->area_sustantiva==0) {	echo "checked"; } ?>/> No Sustantiva
				</div>
			</div>
			<div class="form-group">
				<label class="col-lg-2 control-label">Fecha Inicio</label>
				<div class="col-lg-10">
					<input type="text" id="fecha_ini" name="fecha_ini" value="<?php echo $organigrama->fecha_ini ?>" class="form-control" placeholder="click para ingresar fecha">
				</div>
			</div>
			<div class="form-group">
				<div class="col-lg-12" align="center">
					<button type="submit" class="btn btn-primary">Guardar</button>
					<a href="../" class="btn btn-primary">Cancelar</a>
				</div>
			</div>

		</div>
	</form>

</div>
</div>


<script type="text/javascript">
            // When the document is ready
            $(document).ready(function () {
            	$('#fecha_ini').datepicker({
            		format: "yyyy-mm-dd",
            	});  
            });
</script>
<script type="text/javascript">
	$(function(){
		$('#padre_id').change(function(){
    var id=$(this).val(); //id oficina
    var v=$.ajax({
    	url:'../../ajax/sigla/'+id,
    	type:'POST',
    	datatype: 'json',
	//data:{id:id},
	success: function(data) { $("#sigla").val(data);}, //mostramos el error
	error: function() { alert('Se ha producido un error Inesperado'); }
});
});
	});
</script>