<script type="text/javascript">
/*        $(document).ready(function () {            

        	$("#table").jqxDataTable(
            {
                altRows: true,
                sortable: true,
                selectionMode: 'singleRow',
                pageable: true,
                pagerMode: 'advanced',
                columns: [
                  { text: 'Nro', dataField: 'Nro', width: 50 },
                  { text: 'Unidad', dataField: 'Unidad', width: 400 },
                  { text: 'Sigla', dataField: 'Sigla', width: 250 },
                  { text: 'Adicionar', dataField: 'Adicionar', width: 200, align: 'right', sortable: false,columntype: 'button'}
                ]
            });
        });
*/        
</script>


<script type="text/javascript">
$(document).ready(function () {
		var source =
		{
			datatype: "json",
			datafields: [
				{ name: 'id'},
				{ name: 'unidad_administrativa'},
				{ name: 'sigla'}
			],
			url: '../../organigramas/list',
			cache: false
		};
		var dataAdapter = new $.jqx.dataAdapter(source);
		cargar();	
		function cargar(){
			$("#jqxgrid").jqxGrid(
		{
		width: 950,
		source: dataAdapter,
		sortable: true,
		altRows: true,
		pageable: true,
		pagerMode: 'advanced',
		showfilterrow: true,
		filterable: true,
		columns: [
			{ text: 'Nro', datafield: 'id',filtertype: 'input', width: 100},
			{ text: 'Unidad', datafield: 'unidad_administrativa', filtertype: 'input',width: 550 },
			{ text: 'Sigla', datafield: 'sigla', width: 200 },
			{ text: 'Editar', datafield: 'Editar', sortable:false, columntype: 'button', cellsrenderer: function () {
                     return "Editar";
                  }, buttonclick: function (row) {
                     // open the popup window when the user clicks a button.
                     editrow = row;
                     var offset = $("#jqxgrid").offset();
                     $("#popupWindow").jqxWindow({ position: { x: parseInt(offset.left) + 60, y: parseInt(offset.top) + 60 } });

                     // get the clicked row's data and initialize the input fields.
                     var dataRecord = $("#jqxgrid").jqxGrid('getrowdata', editrow);
                     $("#titulo").text("Editar");
                     $("#id").val(dataRecord.id);
                     $("#padre_id").val(dataRecord.padre_id);
                     $("#da_id").val(dataRecord.da_id);
                     $("#nivel_estructural_id").val(dataRecord.nivel_estructural_id);
                     $("#unidad_administrativa").val(dataRecord.unidad_administrativa);
                     $("#sigla").val(dataRecord.sigla);

                     // show the popup window.
                     $("#popupWindow").jqxWindow('open');
                 }
            },
            { text: 'Eliminar', datafield: 'Eliminar', sortable:false, columntype: 'button', cellsrenderer: function () {
                     return "Eliminar";
                  }, buttonclick: function (row) {
                     editrow = row;
                     var offset = $("#jqxgrid").offset();
                     $("#popupWindow_delete").jqxWindow({ position: { x: parseInt(offset.left) + 60, y: parseInt(offset.top) + 60 } });

                     var dataRecord = $("#jqxgrid").jqxGrid('getrowdata', editrow);
                     $("#id").val(dataRecord.id);
                     $("#popupWindow_delete").jqxWindow('open');
                 }
            }
		]
		});

		}
		
		/*$("#addrowbutton").jqxButton();

		// create new row.
        $("#addrowbutton").bind('click', function () {
                var datainformation = $("#jqxgrid").jqxGrid('getdatainformation');
                var rowscount = datainformation.rowscount;
                editrow = rowscount + 1;
                var datarow = generaterow(rowscount + 1);
                $("#jqxgrid").jqxGrid('addrow', rowscount + 1, generaterow(), 'top');
        });        
		*/
		// initialize the popup window and buttons.
            $("#popupWindow").jqxWindow({
                width: 850,height:500, resizable: false,  isModal: true, autoOpen: false, cancelButton: $("#Cancel"), modalOpacity: 0.01           
            });
            $("#popupWindow_delete").jqxWindow({
                width: 850, resizable: false,  isModal: true, autoOpen: false, cancelButton: $("#Cancel"), modalOpacity: 0.01           
            });
            // update the edited row when the user clicks the 'Save' button.
            $("#add").click(function(){
            	$("#titulo").text("Adicionar");
            	$("#id").val("");
            	$("#padre_id").val("");
            	//$("#da_id").val("");
            	$("#nivel_estructural_id").val("");
                $("#unidad_administrativa").val("");
                $("#sigla").val("");
            	$("#popupWindow").jqxWindow('open');
            });

            $("#Save").click(function () {
            	var fecha_ini = $('#fecha_ini').jqxDateTimeInput('getDate');
              	//alert(date);
                var v=$.ajax({
                    	url:'../../organigramas/save/',
                    	type:'POST',
                    	datatype: 'json',
						data:{id:$("#id").val(),padre_id:$("#padre_id").val(),da_id:$("#da_id").val(),nivel_estructural_id:$("#nivel_estructural_id").val(),unidad_administrativa:$("#unidad_administrativa").val(),sigla:$("#sigla").val(),fecha_ini:fecha_ini},
						success: function(data) { cargar(); //alert('Guardado Correctamente'); 
												}, //mostramos el error
						error: function() { alert('Se ha producido un error Inesperado'); }
					});
                    $("#popupWindow").jqxWindow('hide');
               // }
            });

            $("#Eliminar").click(function () {
            	if (editrow >= 0) {
                    var v=$.ajax({
                    	url:'../../organigramas/delete/',
                    	type:'POST',
                    	datatype: 'json',
						data:{id:$("#id").val()},
						success: function(data) { cargar(); //alert('Guardado Correctamente'); 
												}, //mostramos el error
						error: function() { alert('Se ha producido un error Inesperado'); }
					});
					//$('#jqxgrid').jqxGrid();
                    $("#popupWindow_delete").jqxWindow('hide');
                }
            });

            // create a jqxDateTimeInput.
                $("#fecha_ini").jqxDateTimeInput({width: '250px', height: '25px',formatString:'yyyy-MM-dd'});
                $("#fecha_fin").jqxDateTimeInput({width: '250px', height: '25px'});

	});
</script>

<div class="row">
	<div class="col-lg-12">
		<h1>Organigrama</h1>		
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-body">
				<?php //echo $this->flashSession->output() ?>
				<div style="margin-left: 5px;">
					<div>
						<input id="add" type="button" value=" (+) Adicionar" />
					</div>
				</div>
				<br>
				<div class="table-responsive">
					<div id="jqxgrid"></div>
				</div>

				<div style="margin-top: 30px;">
            		<div id="cellbegineditevent"></div>
            		<div style="margin-top: 10px;" id="cellendeditevent"></div>
       			</div>
				<div id="popupWindow">
					<div id="titulo">Editar</div>
					<div style="overflow: hidden;">
						<table>
							<tr>
								<td align="right">id:</td>
								<td align="left"><input id="id" name="id" type="hidden" /></td>
							</tr>
							<tr>
								<td align="right">Depende de:</td>
								<td align="left"><?php echo $padre ?></td>
							</tr>
							<tr>
								<td align="right">Direccion Administrativa:</td>
								<td align="left"><?php echo $da ?></td>
							</tr>
							<tr>
								<td align="right">Nivel Estructural:</td>
								<td align="left"><?php echo $nivelestructural ?></td>
							</tr>
							<tr>
								<td align="right">Unidad Administrativa:</td>
								<td align="left"><input id="unidad_administrativa" name="unidad_administrativa" type="text" /></td>
							</tr>
							<tr>
								<td align="right">Sigla:</td>
								<td align="left"><input id="sigla" name="sigla" type="text" /></td>
							</tr>
							<tr>
								<td align="right">Fecha Inicio:</td>
								<td align="left"><div id='fecha_ini'></div></td>
							</tr>
							
							<tr>
								<td align="right"></td>
								<td style="padding-top: 10px;" align="right">
								<input style="margin-right: 5px;" type="button" id="Save" value="Save" />
								<input id="Cancel" type="button" value="Cancel" />
								</td>
							</tr>
						</table>
					</div>
				</div>

				<div id="popupWindow_delete">
					<div>Eliminar</div>
					<div style="overflow: hidden;">
						<table>
							<tr>
								<td align="left">Esta seguro de Eliminar el registro</td>
							</tr>
							<tr>
								<td align="right"></td>
								<td style="padding-top: 10px;" align="right">
								<input style="margin-right: 5px;" type="button" id="Eliminar" value="Eliminar" />
								<input id="Cancel" type="button" value="Cancel" />
								</td>
							</tr>
						</table>
					</div>
				</div>

			</div>
		</div>
		
	</div>
</div>

