<div class="row">
	<div class="col-lg-12">
		<h1>Organigrama</h1>		
	</div>
</div>

<div class="row">
<?php echo $this->flashSession->output() ?>
    <div class="col-sm-12 animation-stretchRight">
        <div class="widget">
             <div style="width: 100%;" ><?php echo $lista;?></div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12 animation-stretchRight">
        <div class="widget">
             <div id="chart" class="orgChart"></div>
        </div>
    </div>
</div>
  <script>
    jQuery(document).ready(function() {
        $("#org").jOrgChart({
            chartElement : '#chart',
            dragAndDrop  : true
        });

/*        $("a.prueba").click(function(event) {
    			event.preventDefault();
    			var padre = $(this).attr("padre");
    			alert(padre);
    
			});*/
    });
    </script>