<script type="text/javascript">
	$(document).ready(function () {
		var source =
		{
			datatype: "json",
			datafields: [
			{ name: 'id',type: 'number'},
				{ name: 'resolucion_id',type: 'string'},
				{ name: 'categoria',type: 'string'},
				{ name: 'clase',type: 'number'},
				{ name: 'nivel',type: 'number'},
				{ name: 'denominacion',type: 'string'},
				{ name: 'sueldo'}
				
				],
				url: '/nivelsalariales/list',
				cache: false
			};
			var dataAdapter = new $.jqx.dataAdapter(source);
			cargar();	
			function cargar(){
				$("#jqxgrid").jqxGrid(
				{
					width: '100%',
					source: dataAdapter,
					sortable: true,
					altRows: true,
					pageable: true,
					pagerMode: 'advanced',
					showfilterrow: true,
					filterable: true,
					columns: [
					{ text: 'Nro', datafield: 'id',filtertype: 'number', width: '5%'},
			//{ text: 'Resolucion', datafield: 'resolucion_id', filtertype: 'input',width: '25%' },
			{ text: 'Categoria', datafield: 'categoria', filtertype: 'input',width: '25%' },
			{ text: 'Clase', datafield: 'clase', filtertype: 'number',width: '5%' },
			{ text: 'Nivel', datafield: 'nivel', filtertype: 'number',width: '5%' },
			{ text: 'Denominacion', datafield: 'denominacion', filtertype: 'input',width: '30%' },
			{ text: 'Sueldo', datafield: 'sueldo', filtertype: 'number',width: '10%' },
			{ text: 'Editar', datafield: 'Editar', width: '5%',sortable:false, columntype: 'button',filterable:false, cellsrenderer: function () {
				return "Editar";
			}, buttonclick: function (row) {
                     // open the popup window when the user clicks a button.
                     editrow = row;
                     var dataRecord = $("#jqxgrid").jqxGrid('getrowdata', editrow);
                     $("#titulo").text("Editar");
                     $("#id").val(dataRecord.id);
                     $("#resolucion_id").val(dataRecord.resolucion_id);
                     $("#categoria").val(dataRecord.categoria);
                     $("#clase").val(dataRecord.clase);
                     $("#nivel").val(dataRecord.nivel);
                     $("#denominacion").val(dataRecord.denominacion);
                     $("#sueldo").val(dataRecord.sueldo);
                     $('#myModal').modal('show');


                 }
             },
             { text: 'Perfiles Cargos', datafield: 'Perfiles',width:'7%', sortable:false, columntype: 'button', filterable:false,cellsrenderer: function () {
             	return "Perfiles";
             }, buttonclick: function (row) {
             	editrow = row;
             	var offset = $("#jqxgrid").offset();
             	$("#popupWindow_perfil").jqxWindow({ position: { x: parseInt(offset.left) + 30, y: parseInt(offset.top) + 30 } });
             	var dataRecord = $("#jqxgrid").jqxGrid('getrowdata', editrow);
             	$("#id").val(dataRecord.id);
             	
             	var v=$.ajax({
            			url:'/nivelsalariales/setCargosPerfiles/',
            			type:'POST',
            			datatype: 'json',
            			data:{id:dataRecord.id},
						success: function(data) { 
							var res = jQuery.parseJSON(data);
							if(res.length>0){
								$.each( res, function( key, valo ) {
 								$("#perfil_id").val(valo.id);
 								$("#formacion_academica").val(valo.formacion_academica);
 								$("#exp_general_lic").val(valo.exp_general_lic);
 								$("#exp_general_tec").val(valo.exp_general_tec);
 								$("#exp_profesional_lic").val(valo.exp_profesional_lic);
 								$("#exp_profesional_tec").val(valo.exp_profesional_tec);
 								$("#exp_relacionado_lic").val(valo.exp_relacionado_lic);
 								$("#exp_relacionado_tec").val(valo.exp_relacionado_tec);
 								$("#formacion_academica0").val(valo.formacion_academica0);
 								$("#exp_general_lic0").val(valo.exp_general_lic0);
 								$("#exp_general_tec0").val(valo.exp_general_tec0);
 								$("#exp_profesional_lic0").val(valo.exp_profesional_lic0);
 								$("#exp_profesional_tec0").val(valo.exp_profesional_tec0);
 								$("#exp_relacionado_lic0").val(valo.exp_relacionado_lic0);
 								$("#exp_relacionado_tec0").val(valo.exp_relacionado_tec0);
 								});	
							}else{
								$("#perfil_id").val("");
 								$("#formacion_academica").val("");
 								$("#exp_general_lic").val("");
 								$("#exp_general_tec").val("");
 								$("#exp_profesional_lic").val("");
 								$("#exp_profesional_tec").val("");
 								$("#exp_relacionado_lic").val("");
 								$("#exp_relacionado_tec").val("");
 								$("#formacion_academica0").val("");
 								$("#exp_general_lic0").val("");
 								$("#exp_general_tec0").val("");
 								$("#exp_profesional_lic0").val("");
 								$("#exp_profesional_tec0").val("");
 								$("#exp_relacionado_lic0").val("");
 								$("#exp_relacionado_tec0").val("");
							}
							
						}, //mostramos el error
												error: function() { alert('Se ha producido un error Inesperado'); }
				});

                $("#tituloPerfil").text("PERFIL GENERICO DE CARGOS / "+dataRecord.denominacion + " / "+ dataRecord.sueldo +"Bs.");
                var offset = $("#jqxgrid").offset();
             	$("#popupWindow_perfil").jqxWindow({ position: { x: parseInt(offset.left) + 60, y: parseInt(offset.top) + 60 } });
                $("#popupWindow_perfil").jqxWindow('open');
                     
                 }


            },
             { text: 'Eliminar', datafield: 'Eliminar',width:'5%', sortable:false, columntype: 'button', filterable:false,cellsrenderer: function () {
             	return "Eliminar";
             }, buttonclick: function (row) {
             	editrow = row;
             	var dataRecord = $("#jqxgrid").jqxGrid('getrowdata', editrow);
             	$("#id").val(dataRecord.id);
             	bootbox.confirm("<strong>¡Mensaje!</strong> Esta seguro de eliminar el registro.", function(result) {
             		if (result==true) {
             			var v=$.ajax({
             				url:'../../nivelsalariales/delete/',
             				type:'POST',
             				datatype: 'json',
             				data:{id:$("#id").val()},
						success: function(data) { cargar(); //alert('Guardado Correctamente'); 
												}, //mostramos el error
												error: function() { alert('Se ha producido un error Inesperado'); }
											});
             		}
             	});
             }
         }
         ]
     });

}

		$("#popupWindow_perfil").jqxWindow({
			width: 850,height:600, resizable: false,  isModal: true, autoOpen: false, cancelButton: $("#Cancel"), modalOpacity: 0.01           
		});


            $("#add").click(function(){
            	$("#titulo").text("Adicionar");
            	$("#resolucion_id").val("");
            	$("#categoria").val("");
            	$("#clase").val("");
            	$("#nivel").val("");
            	$("#denominacion").val("");
            	$("#sueldo").val("");
            	$('#myModal').modal('show');
			});


            $("#Guardar").click(function () {
            	
            	var v=$.ajax({
            		url:'/nivelsalariales/savePerfil/',
            		type:'POST',
            		datatype: 'json',
            		data:{perfil_id:$("#perfil_id").val(),nivelsalarial_id:$("#id").val(),formacion_academica:$("#formacion_academica").val(),exp_general_lic:$("#exp_general_lic").val(),exp_general_tec:$("#exp_general_tec").val(),exp_profesional_lic:$("#exp_profesional_lic").val(),exp_profesional_tec:$("#exp_profesional_tec").val(),exp_relacionado_lic:$("#exp_relacionado_lic").val(),exp_relacionado_tec:$("#exp_relacionado_tec").val(),formacion_academica0:$("#formacion_academica0").val(),exp_general_lic0:$("#exp_general_lic0").val(),exp_general_tec0:$("#exp_general_tec0").val(),exp_profesional_lic0:$("#exp_profesional_lic0").val(),exp_profesional_tec0:$("#exp_profesional_tec0").val(),exp_relacionado_lic0:$("#exp_relacionado_lic0").val(),exp_relacionado_tec0:$("#exp_relacionado_tec0").val()},
						success: function(data) { cargar(); //alert(data); 
												}, //mostramos el error
												error: function() { alert('Se ha producido un error Inesperado'); }
				});
            	$("#popupWindow_perfil").jqxWindow('hide');
               
           });

$('#testForm').validate({
	rules: {
		resolucion_id: {
			required: true
		},
		categoria: {
			required: true
		},
		denominacion: {
			required: true
		},
		clase: {
			required: true
		},
		nivel: {
			required: true
		},
		sueldo: {
			required: true
		}
	},
	highlight: function (element) {
		$(element).closest('.control-group').removeClass('success').addClass('error');
	},
	success: function (element) {
        //element.text('OK!').addClass('valid').closest('.control-group').removeClass('error').addClass('success');
        element.addClass('valid').closest('.control-group').removeClass('error').addClass('success');
    },
    submitHandler: function (form) {
            // form validates so do the ajax
            var v=$.ajax({
            	url:'/nivelsalariales/save/',
            	type:'POST',
            	datatype: 'json',
            	data:{id:$("#id").val(),resolucion_id:$("#resolucion_id").val(),categoria:$("#categoria").val(),clase:$("#clase").val(),nivel:$("#nivel").val(),denominacion:$("#denominacion").val(),sueldo:$("#sueldo").val()},
						success: function(data) { cargar(); //alert(data); 
												}, //mostramos el error
												error: function() { alert('Se ha producido un error Inesperado'); }
											});
            $('#myModal').modal('hide');
            return false; // ajax used, block the normal submit
        }
    });		

$("#nivel").blur(function(){
	alert($("#nivel").val())
})

});
</script>

<div class="row">
	<div class="col-lg-12">
		<h1>Niveles Salariales</h1>		
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-body">
				<?php //echo $this->flashSession->output() ?>
				<div style="margin-left: 5px;">
					<div>
						<input id="add" type="button" value=" (+) Adicionar" />
					</div>
				</div>
				<br>
				<div class="table-responsive">
					<div id="jqxgrid"></div>
				</div>

				<div style="margin-top: 30px;">
					<div id="cellbegineditevent"></div>
					<div style="margin-top: 10px;" id="cellendeditevent"></div>
				</div>


				<div id="popupWindow_perfil">
					<div id="tituloPerfil">PERFIL GENERICO DE CARGO</div>
					<div id="page-wrapper">
					<div class="row">
						<div class="col-lg-6">
							<div class="panel panel-default">
							<input type="hidden" name="perfil_id" id="perfil_id" value="">
								<div class="panel-heading">
									AREA SUSTANTIVA O MISIONAL
								</div>
								<div class="panel-body form-horizontal">
									
										<div class="form-group">
								          <div class="col-sm-4" >Formación Academica</div>
								          <div class="col-sm-8">
								            <textarea class="form-control" name="formacion_academica" id="formacion_academica"></textarea>
								          </div>
								        </div>
								        <b>EXPERIENCIA GENERAL</b>
								        <div class="form-group">
							              <div class="col-sm-4" >A Nivel Licenciatura</div>
										  <div class="col-sm-8">
										        <input type="text" class="form-control" name="exp_general_lic" id="exp_general_lic">
										  </div>
							            </div>
							            <div class="form-group">
							              <div class="col-sm-4" >A Nivel Tecnico</div>
										  <div class="col-sm-8">
										        <input type="text" class="form-control" name="exp_general_tec" id="exp_general_tec">
										  </div>
							            </div>
							            <b>EXPERIENCIA PROFESIONAL</b>
								        <div class="form-group">
							              <div class="col-sm-4" >A Nivel Licenciatura</div>
										  <div class="col-sm-8">
										        <input type="text" class="form-control" name="exp_profesional_lic" id="exp_profesional_lic">
										  </div>
							            </div>
							            <div class="form-group">
							              <div class="col-sm-4" >A Nivel Tecnico</div>
										  <div class="col-sm-8">
										        <input type="text" class="form-control" name="exp_profesional_tec" id="exp_profesional_tec">
										  </div>
							            </div>
							            <b>EXPERIENCIA EN CARGOS RELACIONADOS</b>
								        <div class="form-group">
							              <div class="col-sm-4" >A Nivel Licenciatura</div>
										  <div class="col-sm-8">
										        <input type="text" class="form-control" name="exp_relacionado_lic" id="exp_relacionado_lic">
										  </div>
							            </div>
							            <div class="form-group">
							              <div class="col-sm-4" >A Nivel Tecnico</div>
										  <div class="col-sm-8">
										        <input type="text" class="form-control" name="exp_relacionado_tec" id="exp_relacionado_tec">
										  </div>
							            </div>
									
								</div>    
							</div>
						</div>
						<div class="col-lg-6">
							<div class="panel panel-default">
								<div class="panel-heading">
									AREA NO SUSTANTIVA
								</div>
								<div class="panel-body form-horizontal" >
									
										<div class="form-group">
								          <div class="col-sm-4" >Formación Academica</div>
								          <div class="col-sm-8">
								            <textarea class="form-control" name="formacion_academica0" id="formacion_academica0"></textarea>
								          </div>
								        </div>
								        <b>EXPERIENCIA GENERAL</b>
								        <div class="form-group">
							              <div class="col-sm-4" >A Nivel Licenciatura</div>
										  <div class="col-sm-8">
										        <input type="text" class="form-control" name="exp_general_lic0" id="exp_general_lic0">
										  </div>
							            </div>
							            <div class="form-group">
							              <div class="col-sm-4" >A Nivel Tecnico</div>
										  <div class="col-sm-8">
										        <input type="text" class="form-control" name="exp_general_tec0" id="exp_general_tec0">
										  </div>
							            </div>
							            <b>EXPERIENCIA PROFESIONAL</b>
								        <div class="form-group">
							              <div class="col-sm-4" >A Nivel Licenciatura</div>
										  <div class="col-sm-8">
										        <input type="text" class="form-control" name="exp_profesional_lic0" id="exp_profesional_lic0">
										  </div>
							            </div>
							            <div class="form-group">
							              <div class="col-sm-4" >A Nivel Tecnico</div>
										  <div class="col-sm-8">
										        <input type="text" class="form-control" name="exp_profesional_tec0" id="exp_profesional_tec0">
										  </div>
							            </div>
							            <b>EXPERIENCIA EN CARGOS RELACIONADOS</b>
								        <div class="form-group">
							              <div class="col-sm-4" >A Nivel Licenciatura</div>
										  <div class="col-sm-8">
										        <input type="text" class="form-control" name="exp_relacionado_lic0" id="exp_relacionado_lic0">
										  </div>
							            </div>
							            <div class="form-group">
							              <div class="col-sm-4" >A Nivel Tecnico</div>
										  <div class="col-sm-8">
										        <input type="text" class="form-control" name="exp_relacionado_tec0" id="exp_relacionado_tec0">
										  </div>
							            </div>
									
								</div>    
							</div>
						</div>
					</div>
					<div class="row">
						<div class="form-group">
							<div class="col-lg-12" align="center">
								<input class="btn btn-primary" type="button" id="Guardar" value="Guardar" />
								<input class="btn btn-primary" id="Cancel" type="button" value="Cancel" />
							</div>
						</div>
					</div>
				</div>

				</div>

			</div>

		</div>
	</div>

</div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<form class="form-horizontal" id="testForm" data-toggle="validator"/>
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h4 class="modal-title" id="titulo">Editar</h4>
			</div>
			<div class="modal-body">
				<input id="id" name="id" type="hidden" />
				<div class="form-group">
					<label class="col-md-3 control-label">Resolución</label>
					<div class="col-md-9">
						<?php echo $resolucion; ?>
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-3 control-label">Nivel Salarial</label>
					<div class="col-md-9">
						<input id="nivel" name="nivel" type="number" class="form-control" placeholder="1,2,3.."/>
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-3 control-label">Categoria</label>
					<div class="col-md-9">
						<input id="categoria" name="categoria" type="text" class="form-control" placeholder="SUPERIOR, EJECUTIVO O OPERATIVO"/>
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-3 control-label">Clase</label>
					<div class="col-md-9">
						<input id="clase" name="clase" type="text" class="form-control" placeholder="2°, 3° o 4°"/>
					</div>
				</div>
				
				<div class="form-group">
					<label class="col-md-3 control-label">Denominación del Puesto</label>
					<div class="col-md-9">
						<input id="denominacion" name="denominacion" type="text" class="form-control" />
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-3 control-label">Sueldo Mensual</label>
					<div class="col-md-9">
						<input id="sueldo" name="sueldo" type="number" class="form-control" />
					</div>
				</div>
				<div class="form-group">
					<label class="col-md-3 control-label">Activar</label>
					<div class="col-md-9">
					<label class="switch switch-primary">
						<input id="activo" name="activo" type="checkbox"/>
						<span></span>
					</label>
					
					</div>
				</div>

			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				<button type="submit" class="btn btn-primary" id="Save">Guardar</button>
			</div>
		</form>
	</div>
</div>
</div>
<!-- end  modal -->