<div class="row">
	<div class="col-lg-12">
		<h1>Nivel Salarial - Escala descriptiva del puesto</h1>		
	</div>
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-body">
			<?php echo $this->flashSession->output() ?>
				<div class="table-responsive">
					<table id="dataTables-example">
						<thead>
							<tr>
								<th>Nro</th>
								<th>Resolución</th>
								<th>Categoria</th>
								<th>Clase</th>
								<th>Nivel Salarial</th>
								<th>Denominación del Cargo</th>
								<th>Sueldo</th>
								<th><a href="/nivelsalariales/add/">Adicionar</a></th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($nivelsalarial as $p) { ?>
							<tr class="odd gradeA">
								<td><?php echo $p->id ?></td>
								<td><?php echo $p->resolucion_id ?></td>
								<td><?php echo $p->categoria ?></td>
								<td><?php echo $p->clase ?></td>
								<td><?php echo $p->nivel ?></td>
								<td><?php echo $p->denominacion ?></td>
								<td><?php echo $p->sueldo ?></td>
								<td>
									<a href="../nivelsalariales/edit/<?php echo $p->id ?>">Editar</a>
									<a href="../nivelsalariales/delete/<?php echo $p->id ?>">Eliminar</a>
								</td>
							</tr>
							<?php } ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		
	</div>
</div>

<script>
	$(document).ready(function() {
		$('#dataTables-example').dataTable();
	});
</script>