<script type="text/javascript">
	$(document).ready(function () {
		var source =
		{
			datatype: "json",
			datafields: [
			{ name: 'id',type: 'number'},
				//{ name: 'resolucion_id',type: 'string'},
				{ name: 'categoria',type: 'string'},
				{ name: 'clase',type: 'number'},
				{ name: 'nivel',type: 'number'},
				{ name: 'denominacion',type: 'string'},
				{ name: 'sueldo'}
				
				],
				url: '../../nivelsalariales/list',
				cache: false
			};
			var dataAdapter = new $.jqx.dataAdapter(source);
			cargar();	
			function cargar(){
				$("#jqxgrid").jqxGrid(
				{
					width: '100%',
					source: dataAdapter,
					sortable: true,
					altRows: true,
					pageable: true,
					pagerMode: 'advanced',
					showfilterrow: true,
					filterable: true,
					columns: [
					{ text: 'Nro', datafield: 'id',filtertype: 'number', width: '5%'},
			//{ text: 'Resolucion', datafield: 'resolucion_id', filtertype: 'input',width: '25%' },
			{ text: 'Categoria', datafield: 'categoria', filtertype: 'input',width: '25%' },
			{ text: 'Clase', datafield: 'clase', filtertype: 'number',width: '5%' },
			{ text: 'Nivel', datafield: 'nivel', filtertype: 'number',width: '5%' },
			{ text: 'Denominacion', datafield: 'denominacion', filtertype: 'input',width: '30%' },
			{ text: 'Sueldo', datafield: 'sueldo', filtertype: 'number',width: '10%' },
			{ text: 'Editar', datafield: 'Editar', width: '5%',sortable:false, columntype: 'button',filterable:false, cellsrenderer: function () {
				return "Editar";
			}, buttonclick: function (row) {
                     // open the popup window when the user clicks a button.
                     editrow = row;
                     var offset = $("#jqxgrid").offset();
                     $("#popupWindow").jqxWindow({ position: { x: parseInt(offset.left) + 60, y: parseInt(offset.top) + 60 } });

                     // get the clicked row's data and initialize the input fields.
                     var dataRecord = $("#jqxgrid").jqxGrid('getrowdata', editrow);
                     $("#titulo").text("Editar");
                     $("#id").val(dataRecord.id);
                     $("#resolucion_id").val(dataRecord.resolucion_id);
                     $("#categoria").val(dataRecord.categoria);
                     $("#clase").val(dataRecord.clase);
                     $("#nivel").val(dataRecord.nivel);
                     $("#denominacion").val(dataRecord.denominacion);
                     $("#sueldo").val(dataRecord.sueldo);
                     // show the popup window.
                     $("#popupWindow").jqxWindow('open');
                 }
             },
             { text: 'Perfiles Cargos', datafield: 'Perfiles',width:'7%', sortable:false, columntype: 'button', filterable:false,cellsrenderer: function () {
             	return "Perfiles";
             }, buttonclick: function (row) {
             	editrow = row;
             	var offset = $("#jqxgrid").offset();
             	$("#popupWindow_perfil").jqxWindow({ position: { x: parseInt(offset.left) + 30, y: parseInt(offset.top) + 30 } });
             	var dataRecord = $("#jqxgrid").jqxGrid('getrowdata', editrow);
             	$("#id").val(dataRecord.id);
             	
             	var v=$.ajax({
            			url:'/nivelsalariales/setCargosPerfiles/',
            			type:'POST',
            			datatype: 'json',
            			data:{id:dataRecord.id},
						success: function(data) { 
							var res = jQuery.parseJSON(data);
							if(res.length>0){
								$.each( res, function( key, valo ) {
 								$("#perfil_id").val(valo.id);
 								$("#formacion_academica").val(valo.formacion_academica);
 								$("#exp_general_lic").val(valo.exp_general_lic);
 								$("#exp_general_tec").val(valo.exp_general_tec);
 								$("#exp_profesional_lic").val(valo.exp_profesional_lic);
 								$("#exp_profesional_tec").val(valo.exp_profesional_tec);
 								$("#exp_relacionado_lic").val(valo.exp_relacionado_lic);
 								$("#exp_relacionado_tec").val(valo.exp_relacionado_tec);
 								$("#formacion_academica0").val(valo.formacion_academica0);
 								$("#exp_general_lic0").val(valo.exp_general_lic0);
 								$("#exp_general_tec0").val(valo.exp_general_tec0);
 								$("#exp_profesional_lic0").val(valo.exp_profesional_lic0);
 								$("#exp_profesional_tec0").val(valo.exp_profesional_tec0);
 								$("#exp_relacionado_lic0").val(valo.exp_relacionado_lic0);
 								$("#exp_relacionado_tec0").val(valo.exp_relacionado_tec0);
 								});	
							}else{
								$("#perfil_id").val("");
 								$("#formacion_academica").val("");
 								$("#exp_general_lic").val("");
 								$("#exp_general_tec").val("");
 								$("#exp_profesional_lic").val("");
 								$("#exp_profesional_tec").val("");
 								$("#exp_relacionado_lic").val("");
 								$("#exp_relacionado_tec").val("");
 								$("#formacion_academica0").val("");
 								$("#exp_general_lic0").val("");
 								$("#exp_general_tec0").val("");
 								$("#exp_profesional_lic0").val("");
 								$("#exp_profesional_tec0").val("");
 								$("#exp_relacionado_lic0").val("");
 								$("#exp_relacionado_tec0").val("");
							}
							
						}, //mostramos el error
												error: function() { alert('Se ha producido un error Inesperado'); }
				});

                $("#tituloPerfil").text("PERFIL GENERICO DE CARGOS / "+dataRecord.denominacion + " / "+ dataRecord.sueldo +"Bs.");
                $("#popupWindow_perfil").jqxWindow('open');
                     
                 }


            },
             { text: 'Eliminar', datafield: 'Eliminar',width:'5%', sortable:false, columntype: 'button', filterable:false,cellsrenderer: function () {
             	return "Eliminar";
             }, buttonclick: function (row) {
             	editrow = row;
             	var offset = $("#jqxgrid").offset();
             	$("#popupWindow_delete").jqxWindow({ position: { x: parseInt(offset.left) + 60, y: parseInt(offset.top) + 60 } });

             	var dataRecord = $("#jqxgrid").jqxGrid('getrowdata', editrow);
             	$("#id").val(dataRecord.id);
             	$("#popupWindow_delete").jqxWindow('open');
             }
         }
         ]
     });

}
		// initialize the popup window and buttons.
		$("#popupWindow").jqxWindow({
			width: 850,height:500, resizable: false,  isModal: true, autoOpen: false, cancelButton: $("#Cancel"), modalOpacity: 0.01           
		});
		$("#popupWindow_delete").jqxWindow({
			width: 850, resizable: false,  isModal: true, autoOpen: false, cancelButton: $("#Cancel"), modalOpacity: 0.01           
		});
		$("#popupWindow_perfil").jqxWindow({
			width: 850,height:600, resizable: false,  isModal: true, autoOpen: false, cancelButton: $("#Cancel"), modalOpacity: 0.01           
		});
            // update the edited row when the user clicks the 'Save' button.
            $("#add").click(function(){
            	$("#titulo").text("Adicionar");
            	$("#id").val("");
            	//$("#resolucion_id").val("");
            	$("#categoria").val("");
            	$("#clase").val("");
            	$("#nivel").val("");
            	$("#denominacion").val("");
            	$("#sueldo").val("");
            	/*fecha= new Date();
  				fecha.setDate(fecha.getDate());
				$("#fecha_ini").jqxDateTimeInput('setDate', fecha);
				*/
				$("#popupWindow").jqxWindow('open');				
			});

            $("#Save").click(function () {
            	//var fecha_ini = $('#fecha_ini').jqxDateTimeInput('getDate');
            	var v=$.ajax({
            		url:'../../nivelsalariales/save/',
            		type:'POST',
            		datatype: 'json',
            		data:{id:$("#id").val(),resolucion_id:$("#resolucion_id").val(),categoria:$("#categoria").val(),clase:$("#clase").val(),nivel:$("#nivel").val(),denominacion:$("#denominacion").val(),sueldo:$("#sueldo").val()},
						success: function(data) { cargar(); //alert(data); 
												}, //mostramos el error
												error: function() { alert('Se ha producido un error Inesperado'); }
				});
            	$("#popupWindow").jqxWindow('hide');
               // }
           });

            $("#Eliminar").click(function () {
            	if (editrow >= 0) {
            		var v=$.ajax({
            			url:'../../nivelsalariales/delete/',
            			type:'POST',
            			datatype: 'json',
            			data:{id:$("#id").val()},
						success: function(data) { cargar(); //alert('Guardado Correctamente'); 
												}, //mostramos el error
												error: function() { alert('Se ha producido un error Inesperado'); }
											});
					//$('#jqxgrid').jqxGrid();
					$("#popupWindow_delete").jqxWindow('hide');
				}
			});

            $("#Guardar").click(function () {
            	
            	var v=$.ajax({
            		url:'/nivelsalariales/savePerfil/',
            		type:'POST',
            		datatype: 'json',
            		data:{perfil_id:$("#perfil_id").val(),nivelsalarial_id:$("#id").val(),formacion_academica:$("#formacion_academica").val(),exp_general_lic:$("#exp_general_lic").val(),exp_general_tec:$("#exp_general_tec").val(),exp_profesional_lic:$("#exp_profesional_lic").val(),exp_profesional_tec:$("#exp_profesional_tec").val(),exp_relacionado_lic:$("#exp_relacionado_lic").val(),exp_relacionado_tec:$("#exp_relacionado_tec").val(),formacion_academica0:$("#formacion_academica0").val(),exp_general_lic0:$("#exp_general_lic0").val(),exp_general_tec0:$("#exp_general_tec0").val(),exp_profesional_lic0:$("#exp_profesional_lic0").val(),exp_profesional_tec0:$("#exp_profesional_tec0").val(),exp_relacionado_lic0:$("#exp_relacionado_lic0").val(),exp_relacionado_tec0:$("#exp_relacionado_tec0").val()},
						success: function(data) { cargar(); //alert(data); 
												}, //mostramos el error
												error: function() { alert('Se ha producido un error Inesperado'); }
				});
            	$("#popupWindow_perfil").jqxWindow('hide');
               
           });
    });
</script>

<div class="row">
	<div class="col-lg-12">
		<h1>Niveles Salariales</h1>		
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-body">
				<?php //echo $this->flashSession->output() ?>
				<div style="margin-left: 5px;">
					<div>
						<input id="add" type="button" value=" (+) Adicionar" />
					</div>
				</div>
				<br>
				<div class="table-responsive">
					<div id="jqxgrid"></div>
				</div>

				<div style="margin-top: 30px;">
					<div id="cellbegineditevent"></div>
					<div style="margin-top: 10px;" id="cellendeditevent"></div>
				</div>
				<div id="popupWindow">
					<div id="titulo">Editar</div>
					<div style="overflow: hidden;">
						<table>
							<tr>
								<td align="right">id:</td>
								<td align="left"><input id="id" name="id" type="hidden" /></td>
							</tr>
							<!-- <tr>
								<td align="right">Resolución:</td>
								<td align="left"><?php // echo $resolucion ?></td>
							</tr> -->
							<tr>
								<td align="right">Categoria:</td>
								<td align="left"><input id="categoria" name="categoria" type="text" class="form-control"/></td>
							</tr>
							<tr>
								<td align="right">Clase:</td>
								<td align="left"><input id="clase" name="clase" type="text" class="form-control"/></td>
							</tr>
							<tr>
								<td align="right">Nivel:</td>
								<td align="left"><input id="nivel" name="nivel" type="text" class="form-control"/></td>
							</tr>
							<tr>
								<td align="right">Denominación:</td>
								<td align="left"><input id="denominacion" name="denominacion" type="text" class="form-control"/></td>
							</tr>
							<tr>
								<td align="right">Sueldo:</td>
								<td align="left"><input id="sueldo" name="sueldo" type="text" class="form-control"/></td>
							</tr>
							
							<tr>
								<td align="right"></td>
								<td style="padding-top: 10px;" align="right">
									<input style="margin-right: 5px;" type="button" id="Save" value="Save" />
									<input id="Cancel" type="button" value="Cancel" />
								</td>
							</tr>
						</table>
					</div>
				</div>

				<div id="popupWindow_delete">
					<div>Eliminar</div>
					<div style="overflow: hidden;">
						<table>
							<tr>
								<td align="left">Esta seguro de Eliminar el registro</td>
							</tr>
							<tr>
								<td align="right"></td>
								<td style="padding-top: 10px;" align="right">
									<input style="margin-right: 5px;" type="button" id="Eliminar" value="Eliminar" />
									<input id="Cancel" type="button" value="Cancel" />
								</td>
							</tr>
						</table>
					</div>
				</div>

				<div id="popupWindow_perfil">
					<div id="tituloPerfil">PERFIL GENERICO DE CARGO</div>
					<div id='jqxDockPanel'>
						<input type="hidden" name="perfil_id" id="perfil_id" value="">
						<h4 class="col-lg-12">AREA SUSTANTIVA O MISIONAL</h4>
						<div dock='left' style='background: #E8E8E8;' class="form-horizontal col-lg-12">
							<div class="form-group">
								<label class="col-lg-3 control-label">Formación Academica</label>
								<div class="col-lg-9">
									<input type="text" name="formacion_academica" id="formacion_academica" class="col-lg-12">
								</div>
							</div>
							<div class="form-group">
								<div class="col-lg-12">EXPERIENCIA GENERAL</div>
							</div>
							<div class="form-group">
								<label class="col-lg-3 control-label">A Nivel Licenciatura</label>
								<div class="col-lg-3">
									<input type="text" name="exp_general_lic" id="exp_general_lic"  value="">
								</div>

								<label class="col-lg-3 control-label">A Nivel Tecnico</label>
								<div class="col-lg-3">
									<input type="text" name="exp_general_tec" id="formacion_academica" value="">
								</div>

							</div>
							<div class="form-group">
								<div class="col-lg-12">EXPERIENCIA PROFESIONAL</div>
							</div>
							<div class="form-group">
								<label class="col-lg-3 control-label">A Nivel Licenciatura</label>
								<div class="col-lg-3">
									<input type="text" name="exp_profesional_lic" id="exp_profesional_lic" value="">
								</div>

								<label class="col-lg-3 control-label">A Nivel Tecnico</label>
								<div class="col-lg-3">
									<input type="text" name="exp_profesional_tec" id="exp_profesional_tec" >
								</div>
							</div>
							<div class="form-group">
								<div class="col-lg-12">EXPERIENCIA EN CARGOS RELACIONADOS</div>
							</div>
							<div class="form-group">
								<label class="col-lg-3 control-label">A Nivel Licenciatura</label>
								<div class="col-lg-3">
									<input type="text" name="exp_relacionado_lic" id="exp_relacionado_lic" value="">
								</div>

								<label class="col-lg-3 control-label">A Nivel Tecnico</label>
								<div class="col-lg-3">
									<input type="text" name="exp_relacionado_tec" id="exp_relacionado_tec" value="">
								</div>
							</div>
						</div>

						<h4 class="col-lg-12">AREA NO SUSTANTIVA</h4>             
						<div dock='left' style='background: #E8E8E8;' class="form-horizontal col-lg-12">                 
							<div class="form-group">
								<label class="col-lg-3 control-label">Formación Academica</label>
								<div class="col-lg-9">                     
								<input type="text" name="formacion_academica0" id="formacion_academica0" class="col-lg-12">
								</div>
							</div>
							<div class="form-group">
								<div class="col-lg-12">EXPERIENCIA GENERAL</div>                 
							</div>
							<div class="form-group">                 
								<label class="col-lg-3 control-label">A Nivel Licenciatura</label>                     
								<div class="col-lg-3">
									<input type="text" name="exp_general_lic0" id="exp_general_lic0"  value="">
								</div>

								<label class="col-lg-3 control-label">A Nivel Tecnico</label>
								<div class="col-lg-3">
									<input type="text" name="exp_general_tec0" id="exp_general_tec0" value="">
								</div>

							</div>
							<div class="form-group">
								<div class="col-lg-12">EXPERIENCIA PROFESIONAL</div>
							</div>
							<div class="form-group">
								<label class="col-lg-3 control-label">A Nivel Licenciatura</label>
								<div class="col-lg-3">
									<input type="text" name="exp_profesional_lic0" id="exp_profesional_lic0" value="">
								</div>

								<label class="col-lg-3 control-label">A Nivel Tecnico</label>
								<div class="col-lg-3">
									<input type="text" name="exp_profesional_tec0" id="exp_profesional_tec0" >
								</div>
							</div>
							<div class="form-group">
								<div class="col-lg-12">EXPERIENCIA EN CARGOS RELACIONADOS</div>
							</div>
							<div class="form-group">
								<label class="col-lg-3 control-label">A Nivel Licenciatura</label>
								<div class="col-lg-3">
									<input type="text" name="exp_relacionado_lic0" id="exp_relacionado_lic0" value="">
								</div>

								<label class="col-lg-3 control-label">A Nivel Tecnico</label>
								<div class="col-lg-3">
									<input type="text" name="exp_relacionado_tec0" id="exp_relacionado_tec0" value="">
								</div>
							</div>
						</div>

						<div class="form-group">
							<div class="col-lg-12" align="center">
								<input class="btn btn-primary" type="button" id="Guardar" value="Guardar" />
								<input class="btn btn-primary" id="Cancel" type="button" value="Cancel" />
							</div>
						</div>	

					</div>

				</div>



			</div>

		</div>
	</div>

</div>
</div>

