
<div class="content-header">
    <div class="header-section">
        <h1>
            <i class="gi gi-dashboard"></i>Pagina de Inicio<br><small>Bienvenido: <?php echo $usuario->nombre; ?></small>
        </h1>
    </div>
</div>
<div class="row">
    <div class="col-sm-6 col-lg-3">
        <div class="widget">
            <div class="widget-simple">
                <a href="/correspondencia" class="widget-icon pull-left themed-background animation-fadeIn">
                    <i class="fa fa-users"></i>
                </a>
                <h3 class="widget-content text-right animation-pullDown">
                    Contrato Plazo Indefinido: <strong><?php echo $permanentes; ?></strong><br />
                    <small>Personal Mi Telef&eacute;rico</small>
                </h3>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-lg-3">
        <div class="widget">
            <div class="widget-simple">
                <a href="/correspondencia/pendientes" class="widget-icon pull-left themed-background-amethyst  animation-fadeIn">
                    <i class="fa fa-users"></i>
                </a>
                <h3 class="widget-content text-right animation-pullDown">
                    Contrato Plazo Fijo: <strong><?php echo $eventuales; ?></strong><br />
                    <small>Personal Mi Telef&eacute;rico</small>
                </h3>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-lg-3">
        <div class="widget">
            <div class="widget-simple">
                <a href="./page_ready_inbox.php.html" class="widget-icon pull-left themed-background-night animation-fadeIn">
                    <i class="fa fa-users"></i>
                </a>
                <h3 class="widget-content text-right animation-pullDown">
                    Contrato Por Consultor&iacute;a: <strong><?php echo $consultores; ?></strong><br />
                    <small>Personal Mi Telef&eacute;rico</small>
                </h3>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-lg-3">
        <div class="widget">
            <div class="widget-simple">
                <a href="./page_ready_inbox.php.html" class="widget-icon pull-left themed-background-spring animation-fadeIn">
                    <i class="fa fa-cogs"></i>
                </a>
                <h3 class="widget-content text-right animation-pullDown">
                    Procesos En Ejecuci&oacute;n: <strong><?php echo $procesos_pendientes; ?></strong><br />
                    <small>Procesos Mi Telef&eacute;rico</small>
                </h3>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12 animation-stretchRight">
        <div class="widget">
             <div id="chartdiv" style="width: 100%; height: 400px;">Contenido</div>
        </div>
    </div>
</div>