</head>
<body>
<style>
    .verde {
        color: black \9;
        background-color: #b6ff00 \9;
    }

    .amarillo {
        color: black \9;
        background-color: yellow \9;
    }

    .rojo {
        color: black \9;
        background-color: #e83636 \9;
    }

    .celeste {
        color: black \9;
        background-color: #a8e0ee \9;
    }

    .verde:not(.jqx-grid-cell-hover):not(.jqx-grid-cell-selected), .jqx-widget .green:not(.jqx-grid-cell-hover):not(.jqx-grid-cell-selected) {
        color: black;
        background-color: #b6ff00;
    }

    .amarillo:not(.jqx-grid-cell-hover):not(.jqx-grid-cell-selected), .jqx-widget .yellow:not(.jqx-grid-cell-hover):not(.jqx-grid-cell-selected) {
        color: black;
        background-color: yellow;
    }

    .rojo:not(.jqx-grid-cell-hover):not(.jqx-grid-cell-selected), .jqx-widget .red:not(.jqx-grid-cell-hover):not(.jqx-grid-cell-selected) {
        color: black;
        background-color: #e83636;
    }

    .celeste:not(.jqx-grid-cell-hover):not(.jqx-grid-cell-selected), .jqx-widget .red:not(.jqx-grid-cell-hover):not(.jqx-grid-cell-selected) {
        color: black;
        background-color: #a8e0ee;
    }

    img {
        vertical-align: middle;
    }

    .img-perfil {
        width: 100px;
        height: 130px;
        margin: 0 auto 10 0;
        text-align: center
    }

</style>
<h2 style="padding-top: 0px; width: 100%;"><b>Gesti&oacute;n Perfiles Laborales / Turnos / Calendarios</b></h2>

<div id="divMsjeExito" class="msjs-alert" hidden="hidden">
    <button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
    <h4>
        <i class="fa fa-check-circle"></i>
        &Eacute;xito!
    </h4>
    Solicitud completada!
    <a class="alert-link" href="javascript:void(0)" id="aMsjeExito"></a>
</div>
<div id="divMsjeInformacion" class="msjs-alert" hidden="hidden">
    <button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
    <h4>
        <i class="fa fa-info-circle"></i>
        Atenci&oacute;n!
    </h4>
    Algo que considerar!
    <a class="alert-link" href="javascript:void(0)" id="aMsjeInformacion"></a>
</div>
<div id="divMsjePeligro" class="msjs-alert" hidden="hidden">
    <button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
    <h4>
        <i class="fa fa-exclamation-circle"></i>
        Cuidado!
    </h4>
    Considere lo siguiente!
    <a class="alert-link" href="javascript:void(0)" id="aMsjePeligro"></a>
</div>
<div id="divMsjeError" class="msjs-alert" hidden="hidden">
    <button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
    <h4>
        <i class="fa fa-times-circle"></i>
        Error!
    </h4>
    Solicitud inv&aacute;lida!
    <a class="alert-link" href="javascript:void(0)" id="aMsjeError"></a>
</div>
<div id='jqxTabsPerfilesLaborales'>
<ul>
    <li id="liList">Listado</li>
    <li id="liNew">Nuevo</li>
    <li id="liEdit">Modificaci&oacute;n</li>
    <li id="liTurn">Turnos</li>
    <li id="liCalendar">Calendarios</li>
</ul>
<div class="section" id="divList">
    <form class="navbar-form" id="formNew">
    <div class="form-horizontal">
        <h2>Perfiles Laborales</h2>
    </div>
    <div id='jqxWidget'>
        <div align="right">
            <!--<button class="btn btn-sm btn-primary" type="button" id="btnExportarExcel" accesskey="i">
                <i class="fi fi-xls"></i>
                Exportar Excel
            </button>
            <button class="btn btn-sm btn-primary" type="button" id="btnExportarPDF" accesskey="i">
                <i class="fi fi-pdf"></i>
                Exportar PDF
            </button>-->
            <button class="btn btn-sm btn-primary" type="button" id="btnDesagrupartodo">
                <i class="fa fa-chain-broken"></i>
                Desagrupar Todo
            </button>
            <button class="btn btn-sm btn-primary" type="button" id="btnDesfiltrartodo">
                <i class="gi gi-sorting"></i>
                Desfiltrar Todo
            </button>
        </div>
        <div id="divGridPerfilesLaborales"></div>
    </div>
    </form>
</div>
<div class="section" id="divNew">
    <div class="form-horizontal">
        <h2>Nuevo Perfil Laboral</h2>
    </div>
    <form class="navbar-form" id="formNuevo">
        <br>
        <div class="block full col-sm-12">
            <div class="row div-new-perfil-laboral" id="divPerfilLaboralNuevo">
                <label class="col-sm-3 control-label" for="txtPerilLaboralNuevo">Perfil Laboral *:</label>
                <div class="col-sm-6">
                    <input type="text" id="txtPerfilLaboralNuevo" class="form-control new-perfil-laboral" placeholder="Perfil Laboral">
                    <span class="help-block" id="helpErrorPerfilLaboralNuevo"></span>
                </div>
            </div>
            <div class="row div-new-perfil-laboral" id="divGrupoPerfilLaboralNuevo">
                <label class="col-sm-3 control-label" for="txtGrupoPerfilLaboralNuevo">Grupo:</label>
                <div class="col-sm-6">
                    <input type="text" id="txtGrupoPerfilLaboralNuevo" class="form-control new-perfil-laboral" placeholder="Grupo">
                    <span class="help-block" id="helpErrorGrupoPerfilLaboralNuevo"></span>
                </div>
            </div>
            <div class="row div-new-perfil-laboral" id="divTipoHorarioPerfilLaboralNuevo">
                <label class="col-sm-3 control-label" for="lstTipoHorarioPerfilLaboralNuevo">Tipo Horario *:</label>
                <div class="col-sm-6">
                    <select id="lstTipoHorarioPerfilLaboralNuevo" class="form-control new-perfil-laboral"></select>
                    <span class="help-block" id="helpErrorTipoHorarioPerfilLaboralNuevo"></span>
                </div>
            </div>
            <div class="row" id="divObservacionPerfilLaboralNuevo">
                <label class="col-sm-3 control-label" for="txtObservacionPefilLaboralNuevo">Observaciones :</label>

                <div class="col-sm-6">
                    <textarea placeholder="Observaciones" id="txtObservacionPerfilLaboralNuevo" class="form-control" name="txtObservacionPerfilLaboralNuevo"></textarea>
                </div>
            </div>
        </div>
        <div class="col-sm-9 col-sm-offset-3">
            <button class="btn btn-sm btn-primary" type="button" id="btnGuardarNuevo">
                <i class="fa fa-floppy-o"></i>
                Guardar
            </button>
            <button class="btn btn-sm btn-warning" type="button" id="btnCancelarNuevo">
                <i class="fa fa-repeat"></i>
                Cancelar
            </button>
        </div>

    </form>
</div>
<div class="section" id="divEdit">
    <div class="form-horizontal">
        <h2>Modificaci&oacute;n Perfil Laboral</h2>
    </div>
    <form class="navbar-form" id="formEditar">
        <br>
        <div class="form-horizontal col-sm-12" id="detallesDependenciaEditable">
            <div class="row div-edit-perfil-laboral" id="divPerfilLaboralEditar">
                <label class="col-sm-3 control-label" for="txtPerfilLaboralEditar">Perfil Laboral *:</label>
                <div class="col-sm-6">
                    <input type="text" id="txtPerfilLaboralEditar" class="form-control edit-perfil-laboral">
                    <span class="help-block" id="helpErrorPerfilLaboralEditar"></span>
                </div>
            </div>
            <div class="row div-new-perfil-laboral" id="divGrupoPerfilLaboralEditar">
                <label class="col-sm-3 control-label" for="txtGrupoPerfilLaboralEditar">Grupo:</label>
                <div class="col-sm-6">
                    <input type="text" id="txtGrupoPerfilLaboralEditar" class="form-control edit-perfil-laboral" placeholder="Grupo">
                    <span class="help-block" id="helpErrorGrupoPerfilLaboralEditar"></span>
                </div>
            </div>
            <div class="row div-new-perfil-laboral" id="divTipoHorarioPerfilLaboralEditar">
                <label class="col-sm-3 control-label" for="lstTipoHorarioPerfilLaboralEditar">Tipo Horario *:</label>
                <div class="col-sm-6">
                    <select id="lstTipoHorarioPerfilLaboralEditar" class="form-control edit-perfil-laboral"></select>
                    <span class="help-block" id="helpErrorTipoHorarioPerfilLaboralEditar"></span>
                </div>
            </div>
            <div class="row" id="divObservacionPerfilLaboralEditar">
                <label class="col-sm-3 control-label" for="txtObservacionPerfilLaboralEditar">Observaciones :</label>

                <div class="col-sm-6">
                    <textarea placeholder="Observaciones" id="txtObservacionPerfilLaboralEditar"
                                 name="txtObservacionPerfilLaboralEditar" class="form-control"></textarea>
                </div>
            </div>
        </div>
        <div class="col-sm-9 col-sm-offset-3">
            <button class="btn btn-sm btn-primary" type="button" id="btnGuardarEditar">
                <i class="fa fa-floppy-o"></i>
                Guardar
            </button>
            <button class="btn btn-sm btn-warning" type="button" id="btnCancelarEditar">
                <i class="fa fa-repeat"></i>
                Cancelar
            </button>
        </div>
        <input type="hidden" id="hdnIdPerfilLaboralEditar" value="0">
    </form>
</div>
<div class="section" id="divTurn">
    <form class="navbar-form" id="formTurn">
    <br>
    <div class="widget">
        <div class="widget-simple themed-background-dark">
                <h2 style="color: white">Gesti&oacute;n de Turnos</h2>
                <h4 class="widget-content">
                    <div>
                        <dl class="dl-horizontal" STYLE="color: white;font-size: 13px;">
                            <dt id="dtPerfilLaboralTurnos">Perfil Laboral:</dt>
                            <dd id="ddPerfilLaboralTurnos"></dd>
                            <dt id="dtGrupoTurnos">Grupo:</dt>
                            <dd id="ddGrupoTurnos"></dd>
                            <dt id="dtTipoHorarioTurnos">Tipo de Horario:</dt>
                            <dd id="ddTipoHorarioTurnos"></dd>
                        </dl>
                    </div>
                </h4>
        </div>
    </div>
    <div id='jqxWidgetTurnos' align="center">
        <div align="right">
            <!--<button class="btn btn-sm btn-primary" type="button" id="btnImprimir" accesskey="i">
                <i class="fi fi-xls"></i>
                Exportar Excel
            </button>-->
            <!--<button class="btn btn-sm btn-primary" type="button" id="btnExportarMovilidadPDF" accesskey="i">
                <i class="fi fi-pdf"></i>
                Exportar PDF
            </button>-->
            <button class="btn btn-sm btn-primary" type="button" id="btnDesagruparTodoTemporalidad">
                <i class="fa fa-chain-broken"></i>
                Desagrupar Todo
            </button>
            <button class="btn btn-sm btn-primary" type="button" id="btnDesfiltrarTodoTemporalidad">
                <i class="gi gi-sorting"></i>
                Desfiltrar Todo
            </button>
        </div>
        <div id="jqxgridturnos"></div>
        <div>
            <button class="btn btn-sm btn-warning" type="button" id="btnCancelarTurno">
                <i class="fa fa-reply"></i>
                Volver a Perfiles
            </button>
        </div>
        <div style="margin-top: 30px;">
            <div id="cellbegineditevent"></div>
            <div style="margin-top: 10px;" id="cellendeditevent"></div>
        </div>

    </div>
    </form>
</div>
<div class="section" id="divCalendar">

    <form class="navbar-form" id="formCalendar">
        <br>
        <div class="widget">
            <div class="widget-simple themed-background-dark">
                <h2 style="color: white">Gesti&oacute;n de Calendarios</h2>
                <h4 class="widget-content">
                    <div>
                        <dl class="dl-horizontal" STYLE="color: white;font-size: 13px;">
                            <dt id="dtPerfilLaboralCalendario">Perfil Laboral:</dt>
                            <dd id="ddPerfilLaboralCalendario"></dd>
                            <dt id="dtGrupoCalendario">Grupo:</dt>
                            <dd id="ddGrupoCalendario"></dd>
                            <dt id="dtTipoHorarioCalendario">Tipo de Horario:</dt>
                            <dd id="ddTipoHorarioCalendario"></dd>
                        </dl>
                    </div>
                </h4>
            </div>
        </div>
        <!-- Contenido referente al calendario laboral y gestión de horarios -->
        <div id="page-content">
            <h2 style="padding-top: 0px; width: 100%;"><b><span id="spanPrefijoCalendarioLaboral"></span>Calendario Laboral</b></h2>
            <!-- FullCalendar Content -->
            <div class="block block-alt-noborder full">
                <div class="row">
                    <div class="col-md-2">
                        <!--<div class="block-section">
                            <button type="submit" id="add-event-btn" class="btn btn-primary">Asignar Tolerancia</button>
                        </div>-->
                        <div class="block-section">
                            <div class="block-section text-center text-muted">
                                <small><em><i class="fa fa-arrows"></i> Arrastre y suelte horarios en el calendario</em></small>
                            </div>
                            <ul class="calendar-events" id="ulHorariosEnEspera">
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-10">
                        <div id="calendar"></div>
                        <br>
                        <div id="jqxdropdownbuttontolerancias">
                            <div style="border-color: transparent;" id="jqxgridtolerancias">
                            </div>
                        </div>
                        <input type="hidden" id="hdnIdTolerancia" value="0">
                        <br>
                        <div class="form-group form-actions">
                            <div class="col-md-8 col-md-offset-4">
                                <button id="btnGuardarCalendario" class="btn btn-sm btn-primary" type="button">
                                    <i class="fa fa-floppy-o"></i>
                                    Guardar
                                </button>
                                <button id="btnCancelarCalendario" class="btn btn-sm btn-warning" type="button">
                                    <i class="fa fa-repeat"></i>
                                    Cancelar / Voler a Turnos
                                </button>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
            <!-- END FullCalendar Block -->
            <!-- END FullCalendar Content -->
        </div>
        <!-- END Contenido referente al calendario laboral y gestión de horarios -->


    </form>
</div>
</div>
<!--</form></div>-->
</body>
<div id="divMsjeNotificacionError">
    <div id="divMsjePorError">
    </div>
</div>
<div id="divMsjeNotificacionWarning">
    <div id="divMsjePorWarning">
    </div>
</div>
<div id="divMsjeNotificacionSuccess">
    <div id="divMsjePorSuccess">
    </div>
</div>