<script type="text/javascript">
$(document).ready(function () {
		var source =
		{
			datatype: "json",
			datafields: [
				{ name: 'id',type: 'number'},
				{ name: 'tipo_resolucion',type: 'string'},
				{ name: 'numero_res',type: 'number'},
				{ name: 'fecha_emi',type:'date'},
				{ name: 'fecha_apr',type:'date'}
			],
			url: '/resoluciones/list',
			cache: false
		};
		var dataAdapter = new $.jqx.dataAdapter(source);
		cargar();	
		function cargar(){
			$("#jqxgrid").jqxGrid(
		{
		width: '100%',
		source: dataAdapter,
		sortable: true,
		altRows: true,
		pageable: true,
		pagerMode: 'advanced',
		showfilterrow: true,
		filterable: true,
		columns: [
			{ text: 'Nro', datafield: 'id',filtertype: 'number', width: '5%'},
			{ text: 'Tipo Resolucion', datafield: 'tipo_resolucion', filtertype: 'input',width: '45%' },
			{ text: 'Nro Resolucion', datafield: 'numero_res',filtertype: 'input', width: '10%' },
			{ text: 'Fecha Emision', datafield: 'fecha_emi', filtertype: 'range', width: '10%', cellsalign: 'center', cellsformat: 'dd-MM-yyyy',align:'center'},
			{ text: 'Fecha Aprobación', datafield: 'fecha_apr', filtertype: 'range', width: '10%', cellsalign: 'center', cellsformat: 'dd-MM-yyyy',align:'center'},
			{ text: 'Editar', datafield: 'Editar', width: '5%',sortable:false, columntype: 'button', cellsrenderer: function () {
                     return "Editar";
                  }, buttonclick: function (row) {
                     // open the popup window when the user clicks a button.
                     editrow = row;
                     var offset = $("#jqxgrid").offset();
                     $("#popupWindow").jqxWindow({ position: { x: parseInt(offset.left) + 60, y: parseInt(offset.top) + 60 } });

                     // get the clicked row's data and initialize the input fields.
                     var dataRecord = $("#jqxgrid").jqxGrid('getrowdata', editrow);
                     $("#titulo").text("Editar");
                     $("#id").val(dataRecord.id);
                     $("#tipo_resolucion").val(dataRecord.tipo_resolucion);
                     $("#numero_res").val(dataRecord.numero_res);
					
					$("#fecha_emi").jqxDateTimeInput({ value:dataRecord.fecha_emi,enableBrowserBoundsDetection: false, width: '100%', height: 24, formatString:'dd-MM-yyyy' });	
					$("#fecha_apr").jqxDateTimeInput({ value:dataRecord.fecha_apr,enableBrowserBoundsDetection: false, width: '100%', height: 24, formatString:'dd-MM-yyyy' });	
                     $("#popupWindow").jqxWindow('open');
                     
                 }
            },
            { text: 'Eliminar', datafield: 'Eliminar',width:'5%', sortable:false, columntype: 'button', cellsrenderer: function () {
                     return "Eliminar";
                  }, buttonclick: function (row) {
                     editrow = row;
                     var offset = $("#jqxgrid").offset();
                     $("#popupWindow_delete").jqxWindow({ position: { x: parseInt(offset.left) + 60, y: parseInt(offset.top) + 60 } });

                     var dataRecord = $("#jqxgrid").jqxGrid('getrowdata', editrow);
                     $("#id").val(dataRecord.id);
                     $("#popupWindow_delete").jqxWindow('open');
                 }
            }
		]
		});

		}
		// initialize the popup window and buttons.
            $("#popupWindow").jqxWindow({
                width: 850,height:500, resizable: false,  isModal: true, autoOpen: false, cancelButton: $("#Cancel"), modalOpacity: 0.01           
            });
            $("#popupWindow_delete").jqxWindow({
                width: 850, resizable: false,  isModal: true, autoOpen: false, cancelButton: $("#Cancel"), modalOpacity: 0.01           
            });
            // update the edited row when the user clicks the 'Save' button.
            $("#add").click(function(){
            	$("#titulo").text("Adicionar");
            	$("#id").val("");
            	$("#tipo_resolucion").val("");
            	$("#numero_res").val("");
            	$("#popupWindow").jqxWindow('open');
            	/*fecha= new Date();
  				fecha.setDate(fecha.getDate());
				$("#fecha_emi").jqxDateTimeInput('setDate', fecha);
				fecha= new Date();
  				fecha.setDate(fecha.getDate());
				$("#fecha_apr").jqxDateTimeInput('setDate', fecha);
				*/
            });

            $("#Save").click(function () {
            	if ($('#testForm').jqxValidator('validate')){
            	var fecha_apr = $('#fecha_apr').jqxDateTimeInput('getDate');
            	var fecha_emi = $('#fecha_emi').jqxDateTimeInput('getDate');
            	var v=$.ajax({
                    	url:'../../resoluciones/save/',
                    	type:'POST',
                    	datatype: 'json',
						data:{id:$("#id").val(),tipo_resolucion:$("#tipo_resolucion").val(),numero_res:$("#numero_res").val(),fecha_apr:fecha_apr,fecha_emi:fecha_emi},
						success: function(data) { cargar(); //alert(data); 
												}, //mostramos el error
						error: function() { alert('Se ha producido un error Inesperado'); }
					});
                    $("#popupWindow").jqxWindow('hide');
               }
            });

            $("#Eliminar").click(function () {
            	if (editrow >= 0) {
                    var v=$.ajax({
                    	url:'../../resoluciones/delete/',
                    	type:'POST',
                    	datatype: 'json',
						data:{id:$("#id").val()},
						success: function(data) { cargar(); //alert('Guardado Correctamente'); 
												}, //mostramos el error
						error: function() { alert('Se ha producido un error Inesperado'); }
					});
					//$('#jqxgrid').jqxGrid();
                    $("#popupWindow_delete").jqxWindow('hide');
                }
            });

            $('#testForm').jqxValidator({
                rules: [
                       { input: '#tipo_resolucion', message: 'Campo requerido!', action: 'keyup, blur', rule: 'required' },
                       { input: '#numero_res', message: 'Campo requerido!', action: 'keyup, blur', rule: 'required' },
                       ]
            });

            // create a jqxDateTimeInput.
            //var f='2014-01-01'; 
               	$("#fecha_emi").jqxDateTimeInput({width: '250px', height: '25px',formatString:'dd-MM-yyyy'});
                $("#fecha_apr").jqxDateTimeInput({width: '250px', height: '25px',formatString:'dd-MM-yyyy'});
	});
</script>

<div class="row">
	<div class="col-lg-12">
		<h1>Resoluciones</h1>		
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-body">
				<?php //echo $this->flashSession->output() ?>
				<div style="margin-left: 5px;">
					<div>
						<input id="add" type="button" value=" (+) Adicionar" />
					</div>
				</div>
				<br>
				<div class="table-responsive">
					<div id="jqxgrid"></div>
				</div>

				<div style="margin-top: 30px;">
            		<div id="cellbegineditevent"></div>
            		<div style="margin-top: 10px;" id="cellendeditevent"></div>
       			</div>
				<div id="popupWindow">
					<div id="titulo">Editar</div>
					<div style="overflow: hidden;">
						<form id="testForm">
						<table>
							<tr>
								<td align="right">id:</td>
								<td align="left"><input id="id" name="id" type="hidden" /></td>
							</tr>
							<tr>
								<td align="right">Tipo Resolución:</td>
								<td align="left"><input id="tipo_resolucion" name="tipo_resolucion" type="text" class="form-control"/></td>
							</tr>
							<tr>
								<td align="right">Numero Resolución:</td>
								<td align="left"><input id="numero_res" name="numero_res" type="text" class="form-control"/></td>
							</tr>
							<tr>
								<td align="right">Fecha Emisión:</td>
								<td align="left"><div id='fecha_emi'></div></td>
							</tr>
							<tr>
								<td align="right">Fecha Aprobación:</td>
								<td align="left"><div id='fecha_apr'></div></td>
							</tr>
							<tr>
								<td align="right"></td>
								<td style="padding-top: 10px;" align="right">
								<input style="margin-right: 5px;" type="button" id="Save" value="Guardar" />
								<input id="Cancel" type="button" value="Cancelar" />
								</td>
							</tr>
						</table>
						</form>
					</div>
				</div>

				<div id="popupWindow_delete">
					<div>Eliminar</div>
					<div style="overflow: hidden;">
						<table>
							<tr>
								<td align="left">Esta seguro de Eliminar el registro</td>
							</tr>
							<tr>
								<td align="right"></td>
								<td style="padding-top: 10px;" align="right">
								<input style="margin-right: 5px;" type="button" id="Eliminar" value="Eliminar" />
								<input id="Cancel" type="button" value="Cancel" />
								</td>
							</tr>
						</table>
					</div>
				</div>

			</div>
		</div>
		
	</div>
</div>

