<script type="text/javascript">
	$(document).ready(function () {
		var source =
		{
			datatype: "json",
			datafields: [
			{ name: 'id',type: 'number'},
			{ name: 'orden',type: 'number'},
			{ name: 'nivel_estructural',type: 'string'}
			],
			url: '/nivelestructurales/list',
			cache: false
		};
		var dataAdapter = new $.jqx.dataAdapter(source);
		cargar();	
		function cargar(){
			$("#jqxgrid").jqxGrid(
			{
				width: '100%',
				source: dataAdapter,
				sortable: true,
				altRows: true,
				pageable: true,
				pagerMode: 'advanced',
				showfilterrow: true,
				filterable: true,
				columns: [
				{ text: 'Nro', datafield: 'id',filtertype: 'number', width: '5%'},
				{ text: 'Orden', datafield: 'orden', filtertype: 'number',width: '15%' },
				{ text: 'Nivel Estructural', datafield: 'nivel_estructural',filtertype: 'input', width: '70%' },
				{ text: 'Editar', datafield: 'Editar', width: '5%',sortable:false, columntype: 'button',filterable:false, cellsrenderer: function () {
					return "Editar";
				}, buttonclick: function (row) {
				// open the popup window when the user clicks a button.
				editrow = row;
				// var offset = $("#jqxgrid").offset();
				// $("#popupWindow").jqxWindow({ position: { x: parseInt(offset.left) + 60, y: parseInt(offset.top) + 60 } });

				// get the clicked row's data and initialize the input fields.
				var dataRecord = $("#jqxgrid").jqxGrid('getrowdata', editrow);
				$("#titulo").text("Editar");
				$("#id").val(dataRecord.id);
				$("#orden").val(dataRecord.orden);
				$("#nivel_estructural").val(dataRecord.nivel_estructural);
				$('#myModal').modal('show');

				// show the popup window.
				// $("#popupWindow").jqxWindow('open');
			}
		},
		{ text: 'Eliminar', datafield: 'Eliminar',width:'5%', sortable:false, columntype: 'button', filterable:false,cellsrenderer: function () {
			return "Eliminar";
		}, buttonclick: function (row) {
			editrow = row;
				// var offset = $("#jqxgrid").offset();
				// $("#popupWindow_delete").jqxWindow({ position: { x: parseInt(offset.left) + 60, y: parseInt(offset.top) + 60 } });

				var dataRecord = $("#jqxgrid").jqxGrid('getrowdata', editrow);
				$("#id").val(dataRecord.id);
				// $("#popupWindow_delete").jqxWindow('open');
				bootbox.confirm("<strong>¡Mensaje!</strong> Esta seguro de eliminar el registro.", function(result) {
					if (result==true) {
						var v=$.ajax({
							url:'/nivelestructurales/delete/',
							type:'POST',
							datatype: 'json',
							data:{id:$("#id").val()},
				success: function(data) { cargar(); //alert('Guardado Correctamente'); 
				}, //mostramos el error
				error: function() { alert('Se ha producido un error Inesperado'); }
			});
					}
				});
			}
		}
		]
	});

}

// update the edited row when the user clicks the 'Save' button.
$("#add").click(function(){
	$("#titulo").text("Adicionar");
	$("#id").val("");
	$("#orden").val("");
	$("#nivel_estructural").val("");
	$('#myModal').modal('show');
//$("#popupWindow").jqxWindow('open');
});

// $('#testForm').jqxValidator({
// 	rules: [
// 	{ input: '#orden', message: 'Campo requerido!', action: 'keyup, blur', rule: 'required' },
// 	{ input: '#nivel_estructural', message: 'Campo requerido!', action: 'keyup, blur', rule: 'required' },
// 	]
// });

$('#testForm').validate({
    rules: {
        orden: {
            required: true
        },
        nivel_estructural: {
            required: true
        }
    },
    highlight: function (element) {
        $(element).closest('.control-group').removeClass('success').addClass('error');
    },
    success: function (element) {
        //element.text('OK!').addClass('valid').closest('.control-group').removeClass('error').addClass('success');
        element.addClass('valid').closest('.control-group').removeClass('error').addClass('success');
    },
    submitHandler: function (form) {
            // form validates so do the ajax
            //alert("funciono");
            var v=$.ajax({
            	url:'/nivelestructurales/save/',
            	type:'POST',
            	datatype: 'json',
            	data:{id:$("#id").val(),orden:$("#orden").val(),nivel_estructural:$("#nivel_estructural").val()},
				success: function(data) { cargar(); //alert(data); 
				}, //mostramos el error
			error: function() { alert('Se ha producido un error Inesperado'); }
			});
            $('#myModal').modal('hide');
            return false; // ajax used, block the normal submit
        }
});


});
</script>

<div class="row">
	<div class="col-lg-12">
		<h1>Niveles Estructurales</h1>		
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-body">
				<?php //echo $this->flashSession->output() ?>
				<div style="margin-left: 5px;">
					<div>
						<input id="add" type="button" value=" (+) Adicionar" />
					</div>
				</div>
				<br>
				<div class="table-responsive">
					<div id="jqxgrid"></div>
				</div>

				<!-- Modal -->
				<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
					<div class="modal-dialog">
						<div class="modal-content">
							<form class="form-horizontal" id="testForm" data-toggle="validator"/>
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
								<h4 class="modal-title" id="titulo">Editar</h4>
							</div>
							<div class="modal-body">

								<input id="id" name="id" type="hidden" />
								<div class="form-group">
									<label class="col-md-3 control-label" for="example-hf-email">Orden</label>
									<div class="col-md-9">
										<input id="orden" name="orden" type="number" class="form-control" required/>
									</div>
								</div>
								<div class="form-group">
									<label class="col-md-3 control-label" for="example-hf-password">Nivel Estructural</label>
									<div class="col-md-9">
										<input id="nivel_estructural" name="nivel_estructural" type="text" class="form-control"/>
									</div>
								</div>

							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
								<button type="submit" class="btn btn-primary" id="Save">Guardar</button>
							</div>
						</form>
					</div>
				</div>
			</div>
			<!-- end  modal -->
		</div>
	</div>
</div>
</div>

