<?php
if (isset($_POST['username'])) {
    $user = $_POST['username'];
} else {
    $user = '';
}
?>
<!-- BEGIN ERROR BOX -->
<?php  echo $this->flashSession->output(); ?> 
<div class="alert alert-danger hide">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h4>Error!</h4>
    
</div>
<!-- END ERROR BOX -->
<form action="" method="post">
    <input type="text" name="username" placeholder="Username" value="<?php  echo $user; ?>" class="input-field form-control user" />
    <input type="password" name="password" placeholder="Password" class="input-field form-control password" />
    <button type="submit" class="btn btn-login">Ingresar</button>
</form>
<div class="login-links">
    <a href="/login/password">Olvido su contraseña?</a>
    <br>
    <a href="/login/password">No tengo cuenta? <strong>Registrarme</strong></a>
</div>

