<?php

?>
<script type="text/javascript">
function utf8_encode(argString) {
  //  discuss at: http://phpjs.org/functions/utf8_encode/
  // original by: Webtoolkit.info (http://www.webtoolkit.info/)
  // improved by: Kevin van Zonneveld (http://kevin.vanzonneveld.net)
  // improved by: sowberry
  // improved by: Jack
  // improved by: Yves Sucaet
  // improved by: kirilloid
  // bugfixed by: Onno Marsman
  // bugfixed by: Onno Marsman
  // bugfixed by: Ulrich
  // bugfixed by: Rafal Kukawski
  // bugfixed by: kirilloid
  //   example 1: utf8_encode('Kevin van Zonneveld');
  //   returns 1: 'Kevin van Zonneveld'
  if (argString === null || typeof argString === 'undefined') {
    return '';
  }
  var string = (argString + ''); // .replace(/\r\n/g, "\n").replace(/\r/g, "\n");
  var utftext = '',
    start, end, stringl = 0;
    start = end = 0;
    stringl = string.length;
  for (var n = 0; n < stringl; n++) {
    var c1 = string.charCodeAt(n);
    var enc = null;
    if (c1 < 128) {
      end++;
    } else if (c1 > 127 && c1 < 2048) {
      enc = String.fromCharCode(
        (c1 >> 6) | 192, (c1 & 63) | 128
      );
    } else if ((c1 & 0xF800) != 0xD800) {
      enc = String.fromCharCode(
        (c1 >> 12) | 224, ((c1 >> 6) & 63) | 128, (c1 & 63) | 128
      );
    } else { // surrogate pairs
      if ((c1 & 0xFC00) != 0xD800) {
        throw new RangeError('Unmatched trail surrogate at ' + n);
      }
      var c2 = string.charCodeAt(++n);
      if ((c2 & 0xFC00) != 0xDC00) {
        throw new RangeError('Unmatched lead surrogate at ' + (n - 1));
      }
      c1 = ((c1 & 0x3FF) << 10) + (c2 & 0x3FF) + 0x10000;
      enc = String.fromCharCode(
        (c1 >> 18) | 240, ((c1 >> 12) & 63) | 128, ((c1 >> 6) & 63) | 128, (c1 & 63) | 128
      );
    }
    if (enc !== null) {
      if (end > start) {
        utftext += string.slice(start, end);
      }
      utftext += enc;
      start = end = n + 1;
    }
  }
  if (end > start) {
    utftext += string.slice(start, stringl);
  }
  return utftext;
};
$(document).ready(function () {
    var bdp = 0;
    $("#data_personal").show();
    $("#btn_dat_per").click(function (){
        if (bdp == 0){
            $("#data_personal").hide();
            bdp = 1;
        } else {
            $("#data_personal").show();
            bdp = 0;
        }
    });
    var bdc = 1;
    $("#data_contactos").hide();
    $("#btn_dat_con").click(function (){
        if (bdp == 0){
            $("#data_contactos").hide();
            bdp = 1;
        } else {
            $("#data_contactos").show();
            bdp = 0;
        }
    });
});
</script>
<style>     
    .green {
        color: black\9;
        background-color: #b6ff00\9;
    }
    .yellow {
        color: black\9;
        background-color: yellow\9;
    }
    .red {
        color: black\9;
        background-color: #e83636\9;
    }
    .green:not(.jqx-grid-cell-hover):not(.jqx-grid-cell-selected), .jqx-widget .green:not(.jqx-grid-cell-hover):not(.jqx-grid-cell-selected) {
        color: black;
        background-color: #b6ff00;
    }
    .yellow:not(.jqx-grid-cell-hover):not(.jqx-grid-cell-selected), .jqx-widget .yellow:not(.jqx-grid-cell-hover):not(.jqx-grid-cell-selected) {
        color: black;
        background-color: yellow;
    }
    .red:not(.jqx-grid-cell-hover):not(.jqx-grid-cell-selected), .jqx-widget .red:not(.jqx-grid-cell-hover):not(.jqx-grid-cell-selected) {
        color: black;
        background-color: #e83636;
    }
</style>
<h2 style="padding-top: 0px; width: 100%;"><b>File de Personal.</b></h2>
<div class="block" id="contenedor_principal">
    <div class="block-title">
        <h2><strong>Archivo.</strong></h2>
    </div>
    <div class="block" id="datos_personales">
        <div class="block-title">
            <div class="block-options pull-right">
                <a class="btn btn-alt btn-xs btn-default" title="" id="btn_dat_per" data-toggle="tooltip" href="javascript:void(0)" data-original-title="Contraer/Expandir">
                    <i class="caret"></i>
                </a>
            </div>
            <h3><strong>Datos Personales.</strong></h3>
            <form class="form-horizontal form-bordered" >
                <div class="row" id="data_personal">
                    <div class="col-xs-6">
                        <div class="form-group">
                            <div class="row">
                                <label class="col-xs-4 control-label">Nombres y Apellidos:</label>
                                <div class="col-xs-8">
                                    <p class="form-control-static">Username</p>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-xs-4 control-label">Documento de Identidad:</label>
                                <div class="col-xs-8">
                                    <p class="form-control-static">CI...</p>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-xs-4 control-label">Nacionalidad:</label>
                                <div class="col-xs-8">
                                    <p class="form-control-static">Gentilicio...</p>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-xs-4 control-label">Ciudad de Nacimiento:</label>
                                <div class="col-xs-8">
                                    <p class="form-control-static">Ciudad</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-6">
                        <div class="form-group">
                            <div class="row">
                                <label class="col-xs-4 control-label">Fecha Nacimiento:</label>
                                <div class="col-xs-8">
                                    <p class="form-control-static">dd-mm-yyyy</p>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-xs-4 control-label">Estado Civil:</label>
                                <div class="col-xs-8">
                                    <p class="form-control-static">Civil</p>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-xs-4 control-label">Grupo Sangu&iacute;neo:</label>
                                <div class="col-xs-8">
                                    <p class="form-control-static">Sangre</p>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-xs-4 control-label">Sexo:</label>
                                <div class="col-xs-8">
                                    <p class="form-control-static">M o F</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="block" id="datos_personales">
        <div class="block-title">
            <div class="block-options pull-right">
                <a class="btn btn-alt btn-xs btn-default" title="" id="btn_dat_con" data-toggle="tooltip" href="javascript:void(0)" data-original-title="Contraer/Expandir">
                    <i class="caret"></i>
                </a>
            </div>
            <h3><strong>Datos Personales.</strong></h3>
            <form class="form-horizontal form-bordered" >
                <div class="row" id="data_contactos">
                    <div class="col-xs-6">
                        <div class="form-group">
                            <div class="row">
                                <label class="col-xs-4 control-label">Nombres y Apellidos:</label>
                                <div class="col-xs-8">
                                    <p class="form-control-static">Username</p>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-xs-4 control-label">Documento de Identidad:</label>
                                <div class="col-xs-8">
                                    <p class="form-control-static">CI...</p>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-xs-4 control-label">Nacionalidad:</label>
                                <div class="col-xs-8">
                                    <p class="form-control-static">Gentilicio...</p>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-xs-4 control-label">Ciudad de Nacimiento:</label>
                                <div class="col-xs-8">
                                    <p class="form-control-static">Ciudad</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-6">
                        <div class="form-group">
                            <div class="row">
                                <label class="col-xs-4 control-label">Fecha Nacimiento:</label>
                                <div class="col-xs-8">
                                    <p class="form-control-static">dd-mm-yyyy</p>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-xs-4 control-label">Estado Civil:</label>
                                <div class="col-xs-8">
                                    <p class="form-control-static">Civil</p>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-xs-4 control-label">Grupo Sangu&iacute;neo:</label>
                                <div class="col-xs-8">
                                    <p class="form-control-static">Sangre</p>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-xs-4 control-label">Sexo:</label>
                                <div class="col-xs-8">
                                    <p class="form-control-static">M o F</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>