<!DOCTYPE html>
<html lang="es" class="app">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="Ivan MArcelo">
        <meta name="keyword" content="">
        <link rel="shortcut icon" href="img/favicon.png">
        <?php echo $this->tag->getTitle(); ?>
        <style>
            body{font-family:Roboto,Arial,sans-serif;font-size:11px;font-weight:400;text-decoration:none}
        </style>
        <!-- CSS -->
       <!-- <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'> -->
        <!--[if IE 8]><script src="/assets/js/helpers/excanvas.min.js"></script><![endif]-->
        <!-- <link rel="stylesheet" href="/media/css/styles.css"> -->
        
        <?php $this->assets->outputCss(); ?>
        <!--[if lt IE 9]> <script src="/assets/js/ie/html5shiv.js"></script> <script src="/assets/js/ie/respond.min.js"></script> <script src="/assets/js/ie/excanvas.js"></script> <![endif]-->
        <script src="/assets/js/vendor/jquery-1.11.0.min.js"></script>
        <?php echo $this->assets->outputJs() ?>  
    </head>
    <body>

        <div id="page-container" class="header-fixed-top  footer-fixed sidebar-full ">
            <div id="sidebar" class="">
                <div class="sidebar-scroll">
                    <div class="sidebar-content">
                        <a href="/dashboard" class="sidebar-brand">
                            <i class="fa fa-refresh text-white"></i><strong>SIR-MT </strong>v1
                        </a>
                        <div class="sidebar-section sidebar-user clearfix">
                            <div class="sidebar-user-avatar">
                                <a href="/usuario/profile">
                                    <img src="/assets/img/placeholders/avatars/avatar2.jpg" alt="avatar" />
                                </a>
                            </div>
                            <div class="sidebar-user-name"><?php echo $user->username; ?></div>
                            <div class="sidebar-user-links">
                                <a href="/usuario/profile" data-toggle="tooltip" data-placement="bottom" title="Profile"><i class="gi gi-user"></i></a>
                                <a href="/usuario/mensajes" data-toggle="tooltip" data-placement="bottom" title="Messages"><i class="gi gi-envelope"></i></a>
                                <a href="/usuario/password" data-toggle="modal" class="enable-tooltip" data-placement="bottom" title="Cambiar contraseña"><i class="gi gi-cogwheel"></i></a>
                                <a href="/usuario/logout" data-toggle="tooltip" data-placement="bottom" title="Cessar sesiòn"><i class="gi gi-exit"></i></a>
                            </div>
                        </div>
                        <ul class="sidebar-section sidebar-themes clearfix">
                            <li class="active">
                                <a href="javascript:void(0)" class="themed-background-dark-default themed-border-default" data-theme="default" data-toggle="tooltip" title="Default Blue"></a>
                            </li>
                            <li>
                                <a href="javascript:void(0)" class="themed-background-dark-night themed-border-night" data-theme="css/themes/night.css" data-toggle="tooltip" title="Night"></a>
                            </li>
                            <li>
                                <a href="javascript:void(0)" class="themed-background-dark-amethyst themed-border-amethyst" data-theme="css/themes/amethyst.css" data-toggle="tooltip" title="Amethyst"></a>
                            </li>
                            <li>
                                <a href="javascript:void(0)" class="themed-background-dark-modern themed-border-modern" data-theme="css/themes/modern.css" data-toggle="tooltip" title="Modern"></a>
                            </li>
                            <li>
                                <a href="javascript:void(0)" class="themed-background-dark-autumn themed-border-autumn" data-theme="css/themes/autumn.css" data-toggle="tooltip" title="Autumn"></a>
                            </li>
                            <li>
                                <a href="javascript:void(0)" class="themed-background-dark-flatie themed-border-flatie" data-theme="css/themes/flatie.css" data-toggle="tooltip" title="Flatie"></a>
                            </li>
                            <li>
                                <a href="javascript:void(0)" class="themed-background-dark-spring themed-border-spring" data-theme="css/themes/spring.css" data-toggle="tooltip" title="Spring"></a>
                            </li>
                            <li>
                                <a href="javascript:void(0)" class="themed-background-dark-fancy themed-border-fancy" data-theme="css/themes/fancy.css" data-toggle="tooltip" title="Fancy"></a>
                            </li>
                            <li>
                                <a href="javascript:void(0)" class="themed-background-dark-fire themed-border-fire" data-theme="css/themes/fire.css" data-toggle="tooltip" title="Fire"></a>
                            </li>
                        </ul>
                        <ul class="sidebar-nav">                            
                            <?php
                            // Creating a router
                            $router = new \Phalcon\Mvc\Router();
                            $router->handle();
                            $controller = $router->getControllerName();
                            $menu = array();
                            $id = 0;
                            foreach ($menus as $m):
                                $menu[$m->id][$m->id_submenu]['id'] = $m->id_submenu;
                                $menu[$m->id][$m->id_submenu]['submenu'] = $m->submenu;
                                $menu[$m->id][$m->id_submenu]['accion'] = $m->accion;
                                $menu[$m->id][$m->id_submenu]['descripcion'] = $m->descripcion;
                            endforeach;
                            $sm = 0;
                            ?>
                            <?php foreach ($menus as $m): ?>    

                                <?php if ($id != $m->id): ?>

                                    <?php if (count($menu[$m->id]) > 1): ?>

                                        <li>
                                            <?php if ($controller == $m->controlador): ?>
                                                <a href="#" class="sidebar-nav-menu active" class1="" ><i class="fa fa-angle-left sidebar-nav-indicator"></i><i class="<?php echo $m->icon ?> "></i> <?php echo $m->menu; ?></a> 
                                            <?php else: ?>
                                                <a href="#" class="sidebar-nav-menu" class1="" ><i class="fa fa-angle-left sidebar-nav-indicator"></i><i class="<?php echo $m->icon ?> "></i> <?php echo $m->menu; ?></a> 
                                            <?php endif; ?>

                                            <ul> 
                                                <?php
                                                ksort($menu[$m->id]);
                                                foreach ($menu[$m->id] as $k => $v):
                                                    ?>
                                                    <li>
                                                        <a href="/<?php echo $m->controlador; ?>/<?php echo $menu[$m->id][$k]['accion']; ?>" title="<?php echo $menu[$m->id][$k]['descripcion']; ?>"><?php echo $menu[$m->id][$k]['submenu']; ?></a>        
                                                    </li>    
                                                <?php endforeach; ?>
                                            </ul>
                                        </li>
                                    <?php else: ?>
                                        <li>   
                                            <?php if ($controller == $m->controlador): ?>
                                                <a href="/<?php echo $m->controlador; ?>" class="active " ><i class="<?php echo $m->icon ?> "></i> <?php echo $m->menu; ?></a> 
                                            <?php else: ?>
                                                <a href="/<?php echo $m->controlador; ?>" class=" " ><i class="<?php echo $m->icon ?> "></i> <?php echo $m->menu; ?></a> 
                                            <?php endif; ?>

                                        </li>
                                    <?php endif; ?>
                                    <?php
                                    $id = $m->id;
                                endif;
                                ?>  
                            <?php endforeach; ?>
                        </ul>
                        <div class="sidebar-header">
                            <span class="sidebar-header-options clearfix">
                                <a href="javascript:void(0)" data-toggle="tooltip" title="Refresh"><i class="gi gi-refresh"></i></a>
                            </span>
                            <span class="sidebar-header-title">Actividad Reciente</span>
                        </div>
                        <div class="sidebar-section">
                            <div class="alert alert-success alert-alt">
                                <small>5 min ago</small><br />
                                <i class="fa fa-thumbs-up fa-fw"></i> You had a new sale ($10)
                            </div>
                            <div class="alert alert-info alert-alt">
                                <small>10 min ago</small><br />
                                <i class="fa fa-arrow-up fa-fw"></i> Upgraded to Pro plan
                            </div>
                            <div class="alert alert-warning alert-alt">
                                <small>3 hours ago</small><br />
                                <i class="fa fa-exclamation fa-fw"></i> Running low on space<br /><strong>18GB in use</strong> 2GB left
                            </div>
                            <div class="alert alert-danger alert-alt">
                                <small>Yesterday</small><br />
                                <i class="fa fa-bug fa-fw"></i> <a href="javascript:void(0)">New bug submitted</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="main-container">
                <header class="navbar navbar-default navbar-fixed-top">
                    <ul class="nav navbar-nav-custom">
                        <li class="hidden-xs hidden-sm">
                            <a href="javascript:void(0)" id="sidebar-toggle-lg">
                                <i class="fa fa-list-ul fa-fw"></i>
                            </a>
                        </li>
                        <li class="hidden-md hidden-lg">
                            <a href="javascript:void(0)" id="sidebar-toggle-sm">
                                <i class="fa fa-bars fa-fw"></i>
                            </a>
                        </li>
                        <li class="hidden-md hidden-lg">
                            <a href="./index.php.html">
                                <i class="gi gi-stopwatch fa-fw"></i>
                            </a>
                        </li>
                    </ul>
                    <form action="page_ready_search_results.php" method="post" class="navbar-form-custom" role="search" />
                    <div class="form-group">
                        <input type="text" id="top-search" name="top-search" class="form-control" placeholder="Buscar.." />
                    </div>
                    </form>
                    <ul class="nav navbar-nav-custom pull-right">
                        <li class="dropdown">
                            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="gi gi-settings"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-custom dropdown-options dropdown-menu-right">
                                <li class="dropdown-header text-center">Header Style</li>
                                <li>
                                    <div class="btn-group btn-group-justified btn-group-sm">
                                        <a href="javascript:void(0)" class="btn btn-primary" id="options-header-default">Light</a>
                                        <a href="javascript:void(0)" class="btn btn-primary" id="options-header-inverse">Dark</a>
                                    </div>
                                </li>
                                <li class="dropdown-header text-center">Page Style</li>
                                <li>
                                    <div class="btn-group btn-group-justified btn-group-sm">
                                        <a href="javascript:void(0)" class="btn btn-primary" id="options-main-style">Default</a>
                                        <a href="javascript:void(0)" class="btn btn-primary" id="options-main-style-alt">Alternative</a>
                                    </div>
                                </li>
                                <li class="dropdown-header text-center">Main Layout</li>
                                <li>
                                    <button class="btn btn-sm btn-block btn-primary" id="options-header-top">Fixed Side/Header (Top)</button>
                                    <button class="btn btn-sm btn-block btn-primary" id="options-header-bottom">Fixed Side/Header (Bottom)</button>
                                </li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="/assets/img/placeholders/avatars/avatar2.jpg" alt="<?php echo $user->nombre ?>" /> <i class="fa fa-angle-down"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-custom dropdown-menu-right">
                                <li class="dropdown-header text-center">Account</li>
                                <li>
                                    <a href="./page_ready_timeline.php.html">
                                        <i class="fa fa-clock-o fa-fw pull-right"></i>
                                        <span class="badge pull-right">10</span>
                                        Updates
                                    </a>
                                    <a href="./page_ready_inbox.php.html">
                                        <i class="fa fa-envelope-o fa-fw pull-right"></i>
                                        <span class="badge pull-right">5</span>
                                        Messages
                                    </a>
                                    <a href="./page_ready_pricing_tables.php.html"><i class="fa fa-magnet fa-fw pull-right"></i>
                                        <span class="badge pull-right">3</span>
                                        Subscriptions
                                    </a>
                                    <a href="./page_ready_faq.php.html"><i class="fa fa-question fa-fw pull-right"></i>
                                        <span class="badge pull-right">11</span>
                                        FAQ
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="./page_ready_user_profile.php.html">
                                        <i class="fa fa-user fa-fw pull-right"></i>
                                        Profile
                                    </a>
                                    <a href="#modal-user-settings" data-toggle="modal">
                                        <i class="fa fa-cog fa-fw pull-right"></i>
                                        Settings
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="./login.php.html"><i class="fa fa-ban fa-fw pull-right"></i> Logout</a>
                                </li>
                                <li class="dropdown-header text-center">Activity</li>
                                <li>
                                    <div class="alert alert-success alert-alt">
                                        <small>5 min ago</small><br />
                                        <i class="fa fa-thumbs-up fa-fw"></i> You had a new sale ($10)
                                    </div>
                                    <div class="alert alert-info alert-alt">
                                        <small>10 min ago</small><br />
                                        <i class="fa fa-arrow-up fa-fw"></i> Upgraded to Pro plan
                                    </div>
                                    <div class="alert alert-warning alert-alt">
                                        <small>3 hours ago</small><br />
                                        <i class="fa fa-exclamation fa-fw"></i> Running low on space<br /><strong>18GB in use</strong> 2GB left
                                    </div>
                                    <div class="alert alert-danger alert-alt">
                                        <small>Yesterday</small><br />
                                        <i class="fa fa-bug fa-fw"></i> <a href="javascript:void(0)" class="alert-link">New bug submitted</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    
                        

        
                </header>
                <div id="page-content">                
                    <?php echo $this->getContent(); ?>                  
                </div>                
            </div>
        </div>
    </body>
</html>
