<script type="text/javascript">
	$(document).ready(function () {
		var source =
		{
			datatype: "json",
			datafields: [
			{ name: 'id',type: 'number'},
			{ name: 'resolucion_ministerial_id',type: 'number'},
			{ name: 'organigrama_id',type: 'number'},
			{ name: 'codigo_nivel',type: 'number'},
			{ name: 'codigo',type: 'string'},
			{ name: 'ordenador',type: 'number'},
			{ name: 'cargo',type: 'string'},
			{ name: 'fin_partida_id'},
			{ name: 'estado', type: 'string'},
			{ name: 'jefe', type: 'number'},
			{ name: 'fecha_reg',type:'date',format: 'dd-MM-yyyy'},
			],
			url: '/servercargos/list',
			root: 'Rows',
			beforeprocessing: function (data) {
				source.totalrecords = data[0].TotalRows;
			},
			sort: function () {
				$("#jqxgrid").jqxGrid('updatebounddata', 'sort');
			},
			filter: function () {
				$("#jqxgrid").jqxGrid('updatebounddata', 'filter');
			}
		};
		var dataAdapter = new $.jqx.dataAdapter(source);

			$("#jqxgrid").jqxGrid({
				width: '100%',
				height: '100%',
				source: dataAdapter,
				sortable: true,
				altRows: true,
                columnsresize: true,
                pageable: true,
                pagerMode: 'advanced',
                showfilterrow: true,
                filterable: true,
                autorowheight: true,
                virtualmode: true,
                 rendergridrows: function () {
                    return dataAdapter.records;
                },
                columns: [
                {
                	text: '#', sortable: false, filterable: false, editable: false,
                	groupable: false, draggable: false, resizable: false,
                	datafield: '', columntype: 'number', width: '2%',
                	cellsrenderer: function (row, column, value) {
                		return "<div style='margin:3px;'>" + (value + 1) + "</div>";
                	}
                },
                { text: 'ID', datafield: 'id', filtertype: 'input',width: '10%' },
                { text: 'Organigrama', datafield: 'organigrama_id', filtertype: 'number',width: '20%' },
                { text: 'codigo_nivel', datafield: 'codigo_nivel', filtertype: 'number',width: '15%' },
                { text: 'Cargo', datafield: 'cargo', filtertype: 'input',width: '30%' },
                { text: 'Item', datafield: 'codigo', filtertype: 'input',width: '5%' },
                { text: 'Estado', datafield: 'estado', filtertype: 'checkedlist',width: '7%' },
                { text: 'Fecha', datafield: 'fecha_reg', filtertype: 'range', width: '10%', cellsalign: 'center', cellsformat: 'dd-MM-yyyy',align:'center'},
                ]
            });
		

});
</script>

<div class="row">
	<div class="col-lg-12">
		<h1>Cargos</h1>		
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="table-responsive">
					<div id="jqxgrid"></div>
				</div>
			</div>
		</div>
		
	</div>
</div>